(function(){
'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
var game=null,slot=1,mode='destiny',majorOnly=false,backupMode='export',P='opl-v05-';
var ORIG=['East Blue','North Blue','West Blue','South Blue'],REG=ORIG.concat(['Grand Line','New World']);
var ST=['Force','Vitesse','Agilité','Endurance','Résistance','Réflexes','Discipline','Volonté'];
var SK=['Combat','Sabre','Tir','Navigation','Médecine','Commandement','Discrétion','Science'];
var PL={
'Loguetown':['East Blue',14,['Shells Town','Baratie','Reverse Mountain']],
'Shells Town':['East Blue',8,['Loguetown','Orange Town']],
'Orange Town':['East Blue',9,['Shells Town','Syrup Village']],
'Goa':['East Blue',10,['Shimotsuki','Syrup Village']],
'Shimotsuki':['East Blue',6,['Goa','Baratie']],
'Syrup Village':['East Blue',5,['Orange Town','Goa','Baratie']],
'Baratie':['East Blue',12,['Loguetown','Shimotsuki','Syrup Village']],
'Lvneel':['North Blue',12,['Flevance','Minion Island']],
'Flevance':['North Blue',20,['Lvneel','Minion Island']],
'Minion Island':['North Blue',22,['Flevance','Reverse Mountain']],
'Ohara':['West Blue',8,['Ilusia']],
'Ilusia':['West Blue',14,['Ohara','Reverse Mountain']],
'Baterilla':['South Blue',10,['Torino','Reverse Mountain']],
'Torino':['South Blue',16,['Baterilla']],
'Reverse Mountain':['Grand Line',32,['Loguetown','Minion Island','Ilusia','Baterilla','Twin Cape']],
'Twin Cape':['Grand Line',28,['Reverse Mountain','Whisky Peak']],
'Whisky Peak':['Grand Line',34,['Twin Cape','Little Garden']],
'Little Garden':['Grand Line',39,['Whisky Peak','Drum']],
'Drum':['Grand Line',32,['Little Garden','Alabasta']],
'Alabasta':['Grand Line',37,['Drum','Jaya']],
'Jaya':['Grand Line',43,['Alabasta','Water 7']],
'Water 7':['Grand Line',29,['Jaya','Thriller Bark']],
'Thriller Bark':['Grand Line',48,['Water 7','Sabaody']],
'Sabaody':['Grand Line',45,['Thriller Bark','Fish-Man Island']],
'Fish-Man Island':['Grand Line',44,['Sabaody','Punk Hazard']],
'Punk Hazard':['New World',66,['Fish-Man Island','Dressrosa']],
'Dressrosa':['New World',61,['Punk Hazard','Zou','Whole Cake Island']],
'Zou':['New World',52,['Dressrosa','Wano']],
'Whole Cake Island':['New World',78,['Dressrosa','Wano']],
'Wano':['New World',82,['Zou','Whole Cake Island','Egghead']],
'Egghead':['New World',68,['Wano']]};
var CH=[['Garp','Marine','East Blue',90],['Shanks','Pirates','East Blue',95],['Rayleigh','Pirates','Grand Line',92],['Mihawk','Indépendant','Grand Line',90],['Dragon','Révolutionnaires','Grand Line',98],['Kaido','Pirates','New World',99],['Big Mom','Pirates','New World',99],['Barbe Blanche','Pirates','New World',100]];

var ACTOR_TEMPLATES=[
 {name:'Garp',faction:'Marine',region:'East Blue',base:92,peak:97,growth:1,importance:98,goal:'Former la prochaine génération'},
 {name:'Shanks',faction:'Pirates',region:'East Blue',base:28,peak:96,growth:16,importance:100,goal:'Tracer sa propre route'},
 {name:'Rayleigh',faction:'Pirates',region:'Grand Line',base:95,peak:91,growth:22,importance:94,goal:'Observer la nouvelle ère'},
 {name:'Mihawk',faction:'Indépendant',region:'Grand Line',base:34,peak:94,growth:16,importance:96,goal:'Chercher des adversaires dignes'},
 {name:'Dragon',faction:'Révolutionnaires',region:'Grand Line',base:58,peak:98,growth:14,importance:100,goal:'Étendre le réseau révolutionnaire'},
 {name:'Kaido',faction:'Pirates',region:'New World',base:84,peak:99,growth:10,importance:99,goal:'Accroître sa domination'},
 {name:'Big Mom',faction:'Pirates',region:'New World',base:95,peak:99,growth:8,importance:99,goal:'Étendre son territoire'},
 {name:'Barbe Blanche',faction:'Pirates',region:'New World',base:100,peak:96,growth:22,importance:100,goal:'Protéger sa famille'}
];
var REGION_LINKS={
 'East Blue':['Grand Line'],'North Blue':['Grand Line'],'West Blue':['Grand Line'],'South Blue':['Grand Line'],
 'Grand Line':['East Blue','North Blue','West Blue','South Blue','New World'],'New World':['Grand Line']
};
var CREW_A=['Crimson','Brume','Tempête','Écume','Cendre','Aube','Foudre','Corail','Marée','Fer','Sillage','Astre'];
var CREW_B=['Mantas','Ravens','Sharks','Drakes','Foxes','Wolves','Blades','Corsairs','Comets','Serpents','Bulls','Vultures'];
var WORLD_FACTIONS=['Civil','Marine','Pirates','Chasseur de primes','Révolutionnaires','Gouvernement'];
function det(g,k){return (H(String(g.seed||1)+':'+k)%100000)/100000}
function pairKey(a,b){return[a,b].sort().join('|')}
function initDiplomacy(){
 var d={};
 function set(a,b,v){d[pairKey(a,b)]=v}
 set('Marine','Gouvernement',78);set('Marine','Pirates',-90);set('Marine','Révolutionnaires',-58);set('Marine','Civil',28);set('Marine','Chasseur de primes',18);
 set('Gouvernement','Pirates',-96);set('Gouvernement','Révolutionnaires',-100);set('Gouvernement','Civil',16);set('Gouvernement','Chasseur de primes',12);
 set('Pirates','Révolutionnaires',4);set('Pirates','Civil',-22);set('Pirates','Chasseur de primes',-62);
 set('Révolutionnaires','Civil',14);set('Révolutionnaires','Chasseur de primes',-6);set('Civil','Chasseur de primes',22);
 return d
}
function territorySeed(g,name){
 var region=infStatic(name).region,r=det(g,'territory:'+name),controller='Civil';
 if(['East Blue','North Blue','West Blue','South Blue'].indexOf(region)>=0)controller=r<.56?'Marine':r<.88?'Civil':'Pirates';
 else if(region==='Grand Line')controller=r<.30?'Marine':r<.58?'Civil':r<.89?'Pirates':'Gouvernement';
 else controller=r<.56?'Pirates':r<.76?'Gouvernement':r<.90?'Civil':'Révolutionnaires';
 return{controller:controller,influence:Math.round(48+det(g,'influence:'+name)*34),stability:Math.round(38+det(g,'stability:'+name)*50),contested:false,lastChange:null}
}
function infStatic(n){var p=PL[n]||['East Blue',10,[]];return{region:p[0],danger:p[1],routes:p[2]}}
function makeWorldCrew(g,i){
 var alignment=det(g,'crew:f:'+i),f=alignment<.72?'Pirates':alignment<.87?'Chasseur de primes':'Révolutionnaires',
 region=REG[Math.floor(det(g,'crew:r:'+i)*REG.length)],name=CREW_A[Math.floor(det(g,'crew:a:'+i)*CREW_A.length)]+' '+CREW_B[Math.floor(det(g,'crew:b:'+i)*CREW_B.length)];
 return{id:'crew-'+i,name:name,faction:f,region:region,power:Math.round(14+det(g,'crew:p:'+i)*54),members:Math.round(4+det(g,'crew:m:'+i)*28),morale:Math.round(42+det(g,'crew:o:'+i)*48),bounty:f==='Pirates'?Math.round((8+det(g,'crew:q:'+i)*90)*1000000):0,status:'active',ageMonths:Math.round(det(g,'crew:age:'+i)*90),victories:0,defeats:0}
}
function initLivingWorld(g,w){
 w.factions=w.factions||{};if(w.factions.Civil==null)w.factions.Civil=62;if(w.factions['Chasseur de primes']==null)w.factions['Chasseur de primes']=44;
 w.diplomacy=w.diplomacy||initDiplomacy();w.territories=w.territories||{};Object.keys(PL).forEach(function(n){if(!w.territories[n])w.territories[n]=territorySeed(g,n)});
 w.actors=w.actors||ACTOR_TEMPLATES.map(function(a,i){return{name:a.name,faction:a.faction,region:a.region,base:a.base,peak:a.peak,growth:a.growth,importance:a.importance,goal:a.goal,status:'active',woundMonths:0,influence:Math.round(60+det(g,'actor:i:'+i)*35),actions:0}});
 w.crews=w.crews||Array.from({length:10},function(_,i){return makeWorldCrew(g,i)});
 w.conflicts=w.conflicts||[];w.worldHistory=w.worldHistory||[];w.simRemainder=w.simRemainder||0;w.nextCrewId=w.nextCrewId||w.crews.length;w.globalTension=w.globalTension==null?34:w.globalTension;
 return w
}
function diplomacy(a,b){if(a===b)return 100;if(a==='Indépendant'||b==='Indépendant')return 0;return game.world.diplomacy[pairKey(a,b)]||0}
function actorPower(a){var y=game.world.year||0,t=cl(y/Math.max(1,a.growth),0,1);return a.base+(a.peak-a.base)*t}
var FACTION_KEYS=['Civil','Marine','Pirates','Chasseur de primes','Révolutionnaires','Gouvernement'];
var CAREERS={
Civil:{label:'Civil',salary:2800,specs:['Marchand','Médecin','Navigateur','Scientifique','Artisan','Cuisinier'],ranks:[
 {n:'Apprenti',xp:0,rep:-100,pow:0},{n:'Professionnel',xp:35,rep:5,pow:12},{n:'Confirmé',xp:95,rep:18,pow:20},{n:'Expert',xp:190,rep:35,pow:28},{n:'Maître',xp:330,rep:55,pow:38}]},
Marine:{label:'Marine',salary:4200,specs:['Combat','Navigation','Renseignement','Médecine'],ranks:[
 {n:'Recrue',xp:0,rep:-100,pow:0},{n:'Matelot',xp:28,rep:5,pow:15},{n:'Sous-officier',xp:82,rep:15,pow:24},{n:'Enseigne',xp:155,rep:28,pow:31},{n:'Lieutenant',xp:245,rep:42,pow:39},{n:'Commandant',xp:365,rep:58,pow:48},{n:'Capitaine',xp:520,rep:72,pow:58},{n:'Contre-amiral',xp:710,rep:84,pow:67},{n:'Vice-amiral',xp:950,rep:92,pow:76}]},
Pirates:{label:'Pirates',salary:0,specs:['Combattant','Navigateur','Tireur','Médecin','Quartier-maître'],ranks:[
 {n:'Novice',xp:0,rep:-100,pow:0},{n:'Membre',xp:25,rep:5,pow:16},{n:'Combattant',xp:78,rep:16,pow:25},{n:'Officier',xp:150,rep:30,pow:34},{n:'Bras droit',xp:255,rep:48,pow:44},{n:'Capitaine',xp:390,rep:65,pow:53},{n:'Capitaine renommé',xp:590,rep:82,pow:64}]},
'Chasseur de primes':{label:'Chasseur de primes',salary:0,specs:['Traqueur','Duelliste','Tireur','Investigateur'],ranks:[
 {n:'Indépendant',xp:0,rep:-100,pow:0},{n:'Chasseur licencié',xp:38,rep:6,pow:18},{n:'Chasseur réputé',xp:110,rep:22,pow:29},{n:'Chasseur d’élite',xp:225,rep:42,pow:43},{n:'Maître chasseur',xp:420,rep:66,pow:58}]},
Révolutionnaires:{label:'Révolutionnaires',salary:1200,specs:['Combat','Infiltration','Renseignement','Logistique'],ranks:[
 {n:'Sympathisant',xp:0,rep:-100,pow:0},{n:'Agent',xp:34,rep:6,pow:17},{n:'Officier',xp:100,rep:20,pow:27},{n:'Chef de cellule',xp:205,rep:38,pow:39},{n:'Commandant régional',xp:380,rep:62,pow:53},{n:'Cadre révolutionnaire',xp:620,rep:80,pow:65}]},
Gouvernement:{label:'Gouvernement Mondial',salary:5200,specs:['Administration','Renseignement','Cipher Pol'],ranks:[
 {n:'Agent junior',xp:0,rep:-100,pow:0},{n:'Agent',xp:36,rep:8,pow:16},{n:'Agent senior',xp:105,rep:24,pow:26},{n:'Inspecteur',xp:210,rep:42,pow:36},{n:'Directeur',xp:390,rep:65,pow:48}]}
};
var CP_RANKS=[
 {n:'Agent junior',xp:0,rep:-100,pow:0},{n:'Agent',xp:36,rep:8,pow:16},{n:'Stagiaire Cipher Pol',xp:105,rep:25,pow:28},
 {n:'CP7',xp:230,rep:45,pow:40},{n:'CP9',xp:430,rep:68,pow:56},{n:'Candidat CP0',xp:720,rep:88,pow:70}
];
var MISSIONS={
Civil:[
 {title:'Livraison côtière',danger:16,reward:6500,xp:10,tier:0},{title:'Escorte commerciale',danger:28,reward:12000,xp:16,tier:1},
 {title:'Ouvrir une route commerciale',danger:32,reward:19000,xp:23,tier:2,spec:'Marchand'},{title:'Soigner un équipage blessé',danger:20,reward:15000,xp:22,tier:1,spec:'Médecin'},
 {title:'Cartographier une route dangereuse',danger:35,reward:18000,xp:24,tier:2,spec:'Navigateur'},{title:'Étudier un phénomène rare',danger:30,reward:17000,xp:24,tier:2,spec:'Scientifique'}],
Marine:[
 {title:'Patrouille portuaire',danger:20,reward:9000,xp:12,tier:0},{title:'Escorte navale',danger:31,reward:14000,xp:18,tier:1},
 {title:'Démanteler des contrebandiers',danger:39,reward:19000,xp:25,tier:2},{title:'Intercepter un équipage pirate',danger:52,reward:29000,xp:34,tier:3},
 {title:'Sécuriser un royaume allié',danger:64,reward:42000,xp:46,tier:5},{title:'Opération de renseignement',danger:37,reward:21000,xp:28,tier:2,spec:'Renseignement'}],
Pirates:[
 {title:'Chasse au trésor',danger:25,reward:15000,xp:13,tier:0},{title:'Piller un convoi',danger:40,reward:24000,xp:21,tier:1},
 {title:'Affronter un équipage rival',danger:53,reward:36000,xp:31,tier:2},{title:'Raid contre une base Marine',danger:68,reward:54000,xp:45,tier:4},
 {title:'Prendre le contrôle d’une route',danger:77,reward:72000,xp:56,tier:5},{title:'Voler des cartes marines',danger:43,reward:30000,xp:29,tier:2,spec:'Navigateur'}],
'Chasseur de primes':[
 {title:'Traquer un hors-la-loi',danger:31,reward:18000,xp:15,tier:0},{title:'Capturer un capitaine',danger:48,reward:32000,xp:27,tier:2},
 {title:'Contrat sur une cible dangereuse',danger:62,reward:52000,xp:41,tier:3},{title:'Traque longue distance',danger:45,reward:36000,xp:31,tier:2,spec:'Traqueur'}],
Révolutionnaires:[
 {title:'Acheminer des renseignements',danger:28,reward:2000,xp:15,tier:0},{title:'Évacuer des civils',danger:35,reward:3000,xp:22,tier:1},
 {title:'Saboter une installation',danger:55,reward:5000,xp:34,tier:2},{title:'Libérer une cellule capturée',danger:67,reward:7000,xp:46,tier:4},
 {title:'Infiltrer un poste gouvernemental',danger:49,reward:4000,xp:33,tier:2,spec:'Infiltration'}],
Gouvernement:[
 {title:'Surveillance discrète',danger:24,reward:10000,xp:13,tier:0},{title:'Sécuriser un dignitaire',danger:34,reward:16000,xp:20,tier:1},
 {title:'Récupérer des renseignements sensibles',danger:45,reward:25000,xp:29,tier:2},{title:'Opération classifiée',danger:59,reward:39000,xp:40,tier:3},
 {title:'Mission Cipher Pol',danger:68,reward:48000,xp:49,tier:3,spec:'Cipher Pol'}]
};

var TECH={
'Équilibré':[{id:'garde',name:'Garde adaptative',req:12,skill:'Combat',bonus:3},{id:'contre',name:'Contre opportuniste',req:30,skill:'Combat',bonus:5},{id:'enchaînement',name:'Enchaînement complet',req:55,skill:'Combat',bonus:8}],
'Corps-à-corps':[{id:'impact',name:'Impact direct',req:12,skill:'Combat',bonus:4},{id:'rafale',name:'Rafale rapprochée',req:32,skill:'Combat',bonus:6},{id:'briseur',name:'Briseur de garde',req:58,skill:'Combat',bonus:9}],
'Sabreur':[{id:'coupe',name:'Coupe précise',req:12,skill:'Sabre',bonus:4},{id:'iai',name:'Iai rapide',req:34,skill:'Sabre',bonus:7},{id:'lame-distance',name:'Lame à distance',req:62,skill:'Sabre',bonus:10}],
'Tireur':[{id:'tir-vise',name:'Tir visé',req:12,skill:'Tir',bonus:4},{id:'tir-mobile',name:'Tir en mouvement',req:34,skill:'Tir',bonus:7},{id:'tir-longue',name:'Tir longue portée',req:62,skill:'Tir',bonus:10}],
'Mobile / esquive':[{id:'pas-lateral',name:'Pas latéral',req:12,skill:'Combat',bonus:4},{id:'feinte',name:'Feinte éclair',req:34,skill:'Combat',bonus:7},{id:'angle-mort',name:'Angle mort',req:62,skill:'Combat',bonus:10}]
};
var MATCH={'Corps-à-corps':{'Tireur':6},'Tireur':{'Sabreur':5},'Sabreur':{'Équilibré':4},'Mobile / esquive':{'Sabreur':5},'Équilibré':{'Mobile / esquive':3}};
var HAKI_APPS={
Observation:[[1,'Présence'],[25,'Perception étendue'],[55,'Anticipation'],[80,'Vision du futur naissante']],
Armement:[[1,'Renforcement'],[25,'Revêtement'],[55,'Projection'],[80,'Destruction interne']],
Conquérant:[[1,'Intimidation'],[35,'Décharge ciblée'],[70,'Infusion du Conquérant']]
};
function e(s){return String(s==null?'':s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function cl(n,a,b){return Math.max(a,Math.min(b,n))}
function H(s){var x=2166136261>>>0;String(s).split('').forEach(function(c){x=Math.imul(x^c.charCodeAt(0),16777619)});return x>>>0}
function R(k){k=k||'m';var c=game?(game.rng[k]||0):0,s=(game?game.seed:1)^H(k+':'+c);if(game)game.rng[k]=c+1;var t=s+0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}
function pk(a,k){return a[Math.floor(R(k)*a.length)]}
function inf(n){var p=PL[n||game.player.island]||[game.player.region,10,[]];return{region:p[0],danger:p[1],routes:p[2]}}
function age(){var m=game.player.ageMonths,y=Math.floor(m/12),o=Math.floor(m%12);return y?(y+' an'+(y>1?'s':'')+(o?' et '+o+' mois':'')):(o+' mois')}
function key(){return P+slot}
function save(){if(game)localStorage.setItem(key(),JSON.stringify(game))}
function migrate(g){
 if(!g)return null;var p=g.player||{},w=g.world||{};
 g.version=8;g.lastCombat=g.lastCombat||null;g.rng=g.rng||{};
 p.techniques=p.techniques||[];p.techniqueMastery=p.techniqueMastery||{};p.fruitMastery=p.fruitMastery||0;p.fruitAwakened=!!p.fruitAwakened;p.heldFruit=p.heldFruit||null;p.combatXP=p.combatXP||0;p.hakiApplications=p.hakiApplications||{Observation:[],Armement:[],Conquérant:[]};
 p.haki=p.haki||{Observation:0,Armement:0,Conquérant:0};p.latent=p.latent||{Observation:40,Armement:40,Conquérant:0};p.conditions=p.conditions||[];
 p.factionRep=p.factionRep||{Civil:10,Marine:0,Pirates:0,'Chasseur de primes':0,Révolutionnaires:0,Gouvernement:0};
 FACTION_KEYS.forEach(function(k){if(p.factionRep[k]==null)p.factionRep[k]=0});
 p.careerRecords=p.careerRecords||{};p.specialization=p.specialization||null;p.careerHistory=p.careerHistory||[];p.salaryTotal=p.salaryTotal||0;p.deserterFrom=p.deserterFrom||[];
 if(p.career&&p.career!=='Aucune'&&!p.careerRecords[p.faction])p.careerRecords[p.faction]={xp:p.careerXP||0,months:p.serviceMonths||0,rank:p.rank||firstRank(p.faction),specialization:p.specialization||null,successes:0,failures:0};
 if(p.careerRecords[p.faction]){p.rank=p.careerRecords[p.faction].rank||p.rank;p.specialization=p.careerRecords[p.faction].specialization||p.specialization}
 w.fruits=w.fruits||['Mera Mera no Mi','Ope Ope no Mi','Hie Hie no Mi','Moku Moku no Mi'];w.fruitRegistry=w.fruitRegistry||{};
 w.fruits.forEach(function(n){if(!w.fruitRegistry[n])w.fruitRegistry[n]={status:p.fruit===n?'consumed':'available',holder:p.fruit===n?p.name:null}});
 w=initLivingWorld(g,w);g.player=p;g.world=w;return g
}
function load(i){try{return migrate(JSON.parse(localStorage.getItem(P+i)||'null'))}catch(x){return null}}
function tl(t,d,y){game.timeline.unshift({age:age(),title:t,desc:d,type:y||''});game.timeline=game.timeline.slice(0,100)}
function news(t,d){game.news.unshift({title:t,desc:d});game.news=game.news.slice(0,25)}
function press(){var o={};REG.forEach(function(r){o[r]={Piraterie:20+R('w')*25,Marine:30+R('w')*35,Criminalité:15+R('w')*30,Révolution:5+R('w')*20,Prospérité:40+R('w')*35,Instabilité:10+R('w')*25}});return o}
function make(){
 var seed=Number($('#seedInput').value)||Math.floor(Math.random()*2147483647),origin=mode==='custom'?$('#originInput').value:pk(ORIG,'b');
 game={version:8,seed:seed,rng:{},alive:true,pending:null,mission:null,timeline:[],news:[],relations:[],codex:{people:[],places:[],factions:['Civil'],fruits:[]},world:{year:0,month:0,divergence:0,pressures:{},factions:{Marine:82,Pirates:79,Révolutionnaires:56,Gouvernement:94},canon:[['Exécution de Gol D. Roger',0,'completed',100],['Nouvelle génération',18,'future',75],['Guerre au sommet',22,'future',95]],fruits:['Mera Mera no Mi','Ope Ope no Mi','Hie Hie no Mi','Moku Moku no Mi']},player:{name:$('#nameInput').value.trim()||'Kael Maren',difficulty:$('#difficultyInput').value,ageMonths:0,race:mode==='custom'?$('#raceInput').value:pk(['Humain','Humain','Humain','Mink','Homme-poisson'],'b'),origin:origin,region:origin,island:'',situation:'Enfance',activity:'Grandir',faction:'Civil',career:'Aucune',rank:'Enfant',money:3000,health:100,energy:100,danger:'Faible',conditions:[],bounty:0,highestBounty:0,reputation:0,ambition:'Survivre',wins:0,losses:0,travel:null,visited:[],style:mode==='custom'?$('#styleInput').value:pk(['Équilibré','Corps-à-corps','Sabreur','Tireur','Mobile / esquive'],'b'),fruit:null,heldFruit:null,fruitMastery:0,fruitAwakened:false,techniques:[],techniqueMastery:{},combatXP:0,hakiApplications:{Observation:[],Armement:[],Conquérant:[]},haki:{Observation:0,Armement:0,Conquérant:0},latent:{Observation:20+R('h')*60,Armement:20+R('h')*60,Conquérant:R('h')<.04?90:0},stats:{},skills:{},caps:{}}};
 game=migrate(game);var homes=Object.keys(PL).filter(function(n){return PL[n][0]===origin});game.player.island=pk(homes,'b');game.player.visited=[game.player.island];game.codex.places=[game.player.island];game.world.pressures=press();
 ST.forEach(function(k){game.player.stats[k]=8+R('b')*12;game.player.caps[k]=68+R('c')*25});SK.forEach(function(k){game.player.skills[k]=2+R('b')*8;game.player.caps[k]=68+R('c')*25});
 syncPowers();tl('Naissance','Tu nais à '+game.player.island+', dans '+origin+'.','major');news('Grande Ère de la Piraterie','Le monde entre dans une période de bouleversements.');save();return game}
function diff(){return game.player.difficulty==='Casual'?[1.2,.75]:game.player.difficulty==='Ironman'?[.9,1.55]:[1,1]}
function techniqueBonus(){var p=game.player,b=0;(p.techniques||[]).forEach(function(id){var all=[].concat.apply([],Object.keys(TECH).map(function(k){return TECH[k]})),t=all.find(function(x){return x.id===id});if(t)b+=t.bonus});return b}
function power(){var p=game.player,a=ST.reduce(function(s,k){return s+p.stats[k]},0)/ST.length,b=SK.reduce(function(s,k){return s+p.skills[k]},0)/SK.length,h=p.haki.Observation*.18+p.haki.Armement*.22+p.haki.Conquérant*.27,f=p.fruit?(8+p.fruitMastery*.18+(p.fruitAwakened?12:0)):0;return a*.42+b*.38+h+f+techniqueBonus()*.45}
function powerRank(){var v=power();return v<20?'Novice':v<35?'Combattant':v<50?'Confirmé':v<65?'Élite':v<80?'Monstrueux':'Sommet'}
function syncPowers(){var p=game.player,prof=TECH[p.style]||TECH['Équilibré'];prof.forEach(function(t){if((p.skills[t.skill]||0)>=t.req&&p.techniques.indexOf(t.id)<0){p.techniques.push(t.id);p.techniqueMastery[t.id]=1;tl('Nouvelle technique',t.name+' entre dans ton répertoire.','major')}});Object.keys(HAKI_APPS).forEach(function(k){p.hakiApplications[k]=HAKI_APPS[k].filter(function(a){return p.haki[k]>=a[0]}).map(function(a){return a[1]})})}
function trainHaki(k,m){var p=game.player;if(!p.haki[k]){if(p.latent[k]>55&&R('h')<.025*m*(p.latent[k]/70)){p.haki[k]=1;tl('Éveil du Haki','Ton Haki de '+k+' s’éveille.','major')}return}p.haki[k]=cl(p.haki[k]+m*(.35+p.latent[k]/160)*cl(1-p.haki[k]/125,.12,1),0,100)}
function trainFruit(m){var p=game.player;if(!p.fruit)return;p.fruitMastery=cl(p.fruitMastery+m*(.55+R('fruit')*.45)*cl(1-p.fruitMastery/120,.15,1),0,100);if(p.fruitMastery>=85&&!p.fruitAwakened&&R('fruit')<.015*m){p.fruitAwakened=true;tl('ÉVEIL DU FRUIT','Ta maîtrise franchit un seuil extraordinaire.','major')}}
function learnMastery(m){var p=game.player;(p.techniques||[]).forEach(function(id){p.techniqueMastery[id]=cl((p.techniqueMastery[id]||1)+m*(.4+R('p')*.5),0,100)});syncPowers()}
function gain(k,n){var p=game.player,b=p.stats[k]!=null?p.stats:p.skills,z=b[k],cap=p.caps[k]||90;if(z>=cap)return 0;var g=n*diff()[0]*cl(1-Math.pow(z/110,1.7),.12,1);b[k]=cl(z+g,0,cap);return g}
function train(m){var p=game.player;if(p.activity==='Haki Observation'){trainHaki('Observation',m);learnMastery(m);return}if(p.activity==='Haki Armement'){trainHaki('Armement',m);learnMastery(m);return}if(p.activity==='Haki Conquérant'){trainHaki('Conquérant',m);learnMastery(m);return}if(p.activity==='Maîtrise du Fruit'){trainFruit(m);learnMastery(m);return}var map={Grandir:['Endurance','Réflexes'],Études:['Discipline','Science'],Entraînement:['Force','Combat'],Navigation:['Navigation','Endurance'],Sabre:['Sabre','Réflexes'],'Formation Marine':['Discipline','Combat'],'Formation Pirates':['Combat','Navigation'],'Formation Révolutionnaires':['Discrétion','Commandement'],'Formation Gouvernement':['Discipline','Discrétion'],Médecine:['Médecine','Discipline'],Explorer:['Réflexes','Navigation']},ks=map[p.activity]||[pk(ST,'p'),pk(SK,'p')];ks.forEach(function(k){gain(k,m*(.5+R('p')*.8))});if(p.fruit&&R('fruit')<.5)trainFruit(m*.35);if(p.haki.Observation&&R('h')<.35)trainHaki('Observation',m*.25);if(p.haki.Armement&&R('h')<.35)trainHaki('Armement',m*.25);learnMastery(m)}
function decision(t,txt,ch){game.pending={title:t,text:txt,choices:ch};save();render();showDecision()}
function showDecision(){if(!game.pending)return;$('#decisionTitle').textContent=game.pending.title;$('#decisionText').textContent=game.pending.text;$('#decisionChoices').innerHTML=game.pending.choices.map(function(c,i){return '<button class="choice-btn" data-c="'+i+'"><strong>'+e(c[0])+'</strong><small>'+e(c[1])+'</small></button>'}).join('');$$('[data-c]').forEach(function(b){b.onclick=function(){var c=game.pending.choices[+b.dataset.c];c[2]();game.pending=null;$('#decisionModal').classList.add('hidden');save();render()}});$('#decisionModal').classList.remove('hidden')}
function careerTrack(f,spec){return f==='Gouvernement'&&spec==='Cipher Pol'?CP_RANKS:(CAREERS[f]?CAREERS[f].ranks:CAREERS.Civil.ranks)}
function firstRank(f){var c=CAREERS[f]||CAREERS.Civil;return c.ranks[0].n}
function careerRecord(f){f=f||game.player.faction;var p=game.player;if(!p.careerRecords[f])p.careerRecords[f]={xp:0,months:0,rank:firstRank(f),specialization:null,successes:0,failures:0};return p.careerRecords[f]}
function ownRep(){return game.player.factionRep[game.player.faction]||0}
function standingLabel(v){return v<=-40?'Hostile':v<-10?'Méfiant':v<20?'Neutre':v<45?'Reconnu':v<70?'Estimé':'Allié majeur'}
function adjustRep(f,n){var p=game.player;if(p.factionRep[f]==null)p.factionRep[f]=0;p.factionRep[f]=cl(p.factionRep[f]+n,-100,100)}
function rankIndex(){var p=game.player,t=careerTrack(p.faction,p.specialization),i=t.findIndex(function(r){return r.n===p.rank});return i<0?0:i}
function nextRank(){var t=careerTrack(game.player.faction,game.player.specialization),i=rankIndex();return i<t.length-1?t[i+1]:null}
function activityForFaction(f){return f==='Civil'?'Études':f==='Chasseur de primes'?'Entraînement':f==='Pirates'?'Formation Pirates':f==='Révolutionnaires'?'Formation Révolutionnaires':f==='Gouvernement'?'Formation Gouvernement':'Formation Marine'}
function join(f,r){var p=game.player,old=p.faction,rec=careerRecord(f);p.faction=f;p.career=f;p.rank=rec.rank||r||firstRank(f);p.specialization=rec.specialization||null;p.situation='Carrière';p.activity=activityForFaction(f);if(game.codex.factions.indexOf(f)<0)game.codex.factions.push(f);p.careerHistory.push({age:age(),from:old,to:f});tl('Nouvelle carrière','Tu rejoins '+(CAREERS[f]?CAREERS[f].label:f)+'.','major')}
function career(){decision('Choisir une voie','Ta vie adulte commence. Chaque voie possède désormais ses propres rangs, missions, spécialisations et conséquences.',[
 ['Marine','Carrière structurée, salaire et promotions.',function(){join('Marine','Recrue')}],
 ['Pirate','Prime, équipage et ascension par la réputation.',function(){join('Pirates','Novice')}],
 ['Chasseur de primes','Contrats indépendants et revenus à la mission.',function(){join('Chasseur de primes','Indépendant')}],
 ['Civil','Médecine, commerce, navigation, science et artisanat.',function(){join('Civil','Apprenti')}],
 ['Révolutionnaires','Réseau clandestin, infiltration et opérations politiques.',function(){join('Révolutionnaires','Sympathisant')}],
 ['Gouvernement Mondial','Administration, renseignement et accès potentiel au Cipher Pol.',function(){join('Gouvernement','Agent junior')}]
 ])}
function specEligibility(sp){var p=game.player;if(sp==='Cipher Pol'){if(p.faction!=='Gouvernement')return[false,'Réservé au Gouvernement'];if((p.skills.Discrétion||0)<18||(p.skills.Combat||0)<18)return[false,'Combat 18 + Discrétion 18'];if((p.factionRep.Gouvernement||0)<15)return[false,'Réputation Gouvernement 15']}return[true,'']}
function chooseSpecialization(sp){var p=game.player,rec=careerRecord(),q=specEligibility(sp);if(!q[0])return toast(q[1]);if(rec.specialization&&rec.specialization!==sp){rec.xp*=.9;tl('Réorientation','Tu quittes la spécialisation '+rec.specialization+' pour '+sp+'. Une partie de ton expérience de carrière est perdue.','major')}else if(!rec.specialization)tl('Spécialisation','Tu te spécialises en '+sp+'.','major');rec.specialization=sp;p.specialization=sp;if(p.faction==='Gouvernement'&&sp==='Cipher Pol'&&rankIndex()<2&&rec.xp>=105){p.rank='Stagiaire Cipher Pol';rec.rank=p.rank}save();renderChar()}
function salaryPerMonth(){var p=game.player,c=CAREERS[p.faction]||CAREERS.Civil,i=rankIndex();if(!c.salary)return 0;return Math.round(c.salary*(1+i*.34))}
function specSkill(sp){var m={Combat:'Combat',Combattant:'Combat',Duelliste:'Combat',Navigation:'Navigation',Navigateur:'Navigation',Tireur:'Tir',Médecine:'Médecine',Médecin:'Médecine',Renseignement:'Discrétion',Infiltration:'Discrétion',Investigateur:'Discrétion',Scientifique:'Science',Administration:'Discipline',Logistique:'Commandement','Quartier-maître':'Commandement',Marchand:'Commandement',Artisan:'Science',Cuisinier:'Discipline',Traqueur:'Réflexes','Cipher Pol':'Discrétion'};return m[sp]||null}
function evaluatePromotion(){var p=game.player,rec=careerRecord(),n=nextRank();if(!n)return false;var rep=p.factionRep[p.faction]||0;if(rec.xp<n.xp||rep<n.rep||power()<n.pow)return false;p.rank=n.n;rec.rank=n.n;adjustRep(p.faction,3);tl('PROMOTION','Tu accèdes au rang de '+n.n+' au sein de '+(CAREERS[p.faction]?CAREERS[p.faction].label:p.faction)+'.','major');if(p.faction==='Pirates'&&n.n==='Capitaine')tl('Prise de commandement','Ta réputation te permet désormais d’être reconnu comme capitaine.','major');return true}
function careerTick(m){var p=game.player;if(p.ageMonths<180||p.career==='Aucune')return;var rec=careerRecord();rec.months+=m;var active=p.activity.indexOf('Formation')===0||p.activity==='Études'||p.activity==='Entraînement',base=active?1.25:.55;rec.xp+=m*base*(1+(p.stats.Discipline||0)/260);var sk=specSkill(p.specialization);if(sk)gain(sk,m*.14);var sal=salaryPerMonth()*m;if(sal>0){p.money+=sal;p.salaryTotal+=sal}adjustRep(p.faction,m*.08);evaluatePromotion()}
function careerEligibility(f){var p=game.player;if(f===p.faction)return[false,'Voie actuelle'];if(p.ageMonths<180)return[false,'Carrière accessible à partir de 15 ans'];if(f==='Marine'&&p.bounty>0)return[false,'Une prime active bloque le recrutement'];if(f==='Gouvernement'){if(p.bounty>0)return[false,'Une prime active bloque le recrutement'];if((p.stats.Discipline||0)<18)return[false,'Discipline 18 requise']}if(f==='Chasseur de primes'&&p.bounty>50000)return[false,'Prime trop élevée'];return[true,'']}
function switchCareer(f){var p=game.player,old=p.faction,q=careerEligibility(f);if(!q[0])return toast(q[1]);if(old!=='Civil')adjustRep(old,-16);if((old==='Marine'||old==='Gouvernement')&&(f==='Pirates'||f==='Révolutionnaires')){p.deserterFrom.push(old);p.bounty+=80000;tl('Désertion','Ton changement de camp est considéré comme une trahison. Une prime est émise.','danger')}join(f,firstRank(f));save();render()}
function careerChangeDecision(){var p=game.player,ch=[];FACTION_KEYS.forEach(function(f){if(f===p.faction)return;var q=careerEligibility(f);if(q[0])ch.push([(CAREERS[f]?CAREERS[f].label:f),'Quitter '+(CAREERS[p.faction]?CAREERS[p.faction].label:p.faction)+' pour cette voie.',function(){switchCareer(f)}])});if(!ch.length)return toast('Aucune autre voie n’est accessible actuellement.');ch.push(['Rester','Ne rien changer.',function(){}]);decision('Changer de voie','Un changement de faction peut dégrader tes anciennes relations et, en cas de désertion, créer une prime.',ch)}

function styleEdge(a,b){return(MATCH[a]&&MATCH[a][b])||-((MATCH[b]&&MATCH[b][a])||0)}
function injuryName(sev){if(sev>=3)return pk(['Fracture','Traumatisme','Plaie profonde'],'inj');if(sev===2)return pk(['Entorse','Coupure sérieuse','Contusion profonde'],'inj');return pk(['Ecchymoses','Coupure légère','Douleur musculaire'],'inj')}
function combatProfile(){var p=game.player,weapon=p.style==='Sabreur'?p.skills.Sabre:p.style==='Tireur'?p.skills.Tir:p.skills.Combat,inj=p.conditions.reduce(function(a,c){return a+(c.severity||1)*2},0);return{offense:p.stats.Force*.18+p.stats.Vitesse*.13+p.skills.Combat*.27+weapon*.19+p.haki.Armement*.18+p.haki.Conquérant*.08+(p.fruit?p.fruitMastery*.12:0)+techniqueBonus()*.35,defense:p.stats.Résistance*.2+p.stats.Agilité*.17+p.stats.Réflexes*.18+p.skills.Combat*.16+p.haki.Observation*.22+p.haki.Armement*.08-inj,stamina:p.stats.Endurance*.65+p.energy*.22+p.health*.13}}
function fight(d,t){var p=game.player,styles=['Équilibré','Corps-à-corps','Sabreur','Tireur','Mobile / esquive'],enemyStyle=pk(styles,'f'),terrain=pk(['terrain ouvert','pont de navire','espace étroit','ruelles','terrain accidenté'],'f'),cp=combatProfile(),edge=styleEdge(p.style,enemyStyle),enemyOff=d*(.72+R('f')*.46),enemyDef=d*(.7+R('f')*.44),terrainMod=(terrain==='espace étroit'&&p.style==='Tireur')?-4:(terrain==='terrain ouvert'&&p.style==='Tireur')?4:(terrain==='terrain accidenté'&&p.style==='Mobile / esquive')?4:0,playerScore=cp.offense*.58+cp.defense*.34+cp.stamina*.08+edge+terrainMod+(R('f')-.5)*12,enemyScore=enemyOff*.6+enemyDef*.4+(R('f')-.5)*12,adv=playerScore-enemyScore,chance=cl(.5+adv/100,.03,.97),ok=R('f')<chance,margin=Math.abs(adv)+(R('f')*10),damage=0,outcome='';
 p.energy=cl(p.energy-(5+d*.08),0,100);
 if(ok){p.wins++;p.reputation+=4;p.combatXP+=3+d/18;if(p.faction==='Pirates'){p.bounty+=Math.round(d*1200);p.highestBounty=Math.max(p.highestBounty,p.bounty)}gain('Combat',1+d/42);damage=margin<10?Math.round(2+R('f')*7):Math.round(R('f')*4);p.health=cl(p.health-damage,0,100);outcome=margin>22?'Victoire nette':margin>10?'Victoire':'Victoire difficile';if(p.haki.Armement)trainHaki('Armement',.35);if(p.haki.Observation)trainHaki('Observation',.35);if(p.fruit)trainFruit(.3);tl(t||'Combat',outcome+'. '+(damage?'Tu subis '+damage+'% de dégâts.':'Tu évites les blessures sérieuses.'),'major')}
 else{p.losses++;damage=Math.round(cl(7+(enemyScore-playerScore)*.28+R('f')*18,5,58)*diff()[1]);p.health=cl(p.health-damage,0,100);outcome=damage>35?'Défaite sévère':damage>18?'Défaite':'Repli forcé';if(damage>12){var sev=damage>35?3:damage>22?2:1,inj={name:injuryName(sev),months:sev*(1.5+R('inj')*2),severity:sev};p.conditions.push(inj)}tl(t||'Combat',outcome+'. Tu subis '+damage+'% de dégâts.','danger');if(p.health<=0||R('f')<Math.max(0,(enemyScore-playerScore)/230))die('Mort lors d’un affrontement.')}
 game.lastCombat={title:t||'Combat',outcome:outcome,opponentPower:Math.round((enemyOff+enemyDef)/2),playerPower:Math.round(power()),opponentStyle:enemyStyle,playerStyle:p.style,terrain:terrain,matchup:edge+terrainMod,chance:Math.round(chance*100),damage:damage,log:(edge+terrainMod>2?'Ton style exploite le matchup. ':edge+terrainMod<-2?'Le matchup te désavantage. ':'Le matchup est relativement neutre. ')+(p.haki.Observation?'Ton Observation aide à lire les attaques. ':'')+(p.haki.Armement?' Ton Armement renforce les échanges.':'')};syncPowers();return ok}
function challengeFight(){var p=game.player;if(p.ageMonths<144)return toast('Tu es encore trop jeune pour chercher un vrai défi.');if(p.health<45)return toast('Ta santé est trop basse.');var d=inf().danger+12+R('f')*24;fight(d,'Défi local à '+p.island);save();render();if(!game.alive)deathModal()}
function board(){var p=game.player,a=MISSIONS[p.faction]||MISSIONS.Civil,ri=rankIndex(),spec=p.specialization;var eligible=a.filter(function(m){return m.tier<=ri+1&&(!m.spec||m.spec===spec)});eligible.sort(function(x,y){var xs=x.spec===spec?0:1,ys=y.spec===spec?0:1;return xs-ys||x.tier-y.tier||x.danger-y.danger});return eligible.slice(0,4).map(function(m,i){return{id:i,title:m.title,danger:Math.round(m.danger+inf().danger*.22),reward:Math.round(m.reward*(1+ri*.1)),xp:m.xp,tier:m.tier,spec:m.spec||null,months:1+Math.ceil(m.danger/28)}})}
function startMission(i){if(game.mission||game.player.ageMonths<180)return toast('Mission indisponible.');var m=board()[i];if(!m)return toast('Mission introuvable.');game.mission={title:m.title,danger:m.danger,reward:m.reward,xp:m.xp,tier:m.tier,spec:m.spec,remaining:m.months};game.player.situation='Mission';tl('Mission acceptée',m.title+'.','major');save();render()}
function missionReputation(success,m){var p=game.player,d=success?(5+m.tier*2):-(3+m.tier);adjustRep(p.faction,d);if(success){if(p.faction==='Marine'){adjustRep('Gouvernement',1);adjustRep('Pirates',-1)}if(p.faction==='Pirates'){adjustRep('Marine',-2);adjustRep('Gouvernement',-1)}if(p.faction==='Révolutionnaires')adjustRep('Gouvernement',-2);if(p.faction==='Gouvernement')adjustRep('Révolutionnaires',-2);if(p.faction==='Chasseur de primes')adjustRep('Civil',1)}}
function resolveMission(){var m=game.mission,p=game.player,rec=careerRecord(),ok=fight(m.danger,'Mission : '+m.title);if(!game.alive)return;if(ok){p.money+=m.reward;p.reputation+=6;rec.xp+=m.xp;rec.successes++;missionReputation(true,m);tl('Mission accomplie',m.title+' est terminée avec succès. +'+m.xp+' XP carrière.','major')}else{rec.xp+=Math.round(m.xp*.25);rec.failures++;missionReputation(false,m);tl('Mission échouée',m.title+' échoue. La hiérarchie en tient compte.','danger')}game.mission=null;p.situation='Carrière';evaluatePromotion()}

function req(d){var r=inf(d).region,p=game.player;if(r==='Grand Line'&&p.skills.Navigation<18)return[false,'Navigation 18'];if(r==='New World'&&(p.skills.Navigation<35||power()<35))return[false,'Navigation 35 + puissance 35'];return[true,'']}
function go(d){var q=req(d);if(!q[0])return toast('Accès verrouillé : '+q[1]);var z=inf(d).danger,mo=Math.max(.5,Math.round((.6+z/35+R('t')*.8)*10)/10);decision('Prendre la mer','Voyager vers '+d+' prendra environ '+mo+' mois.',[['Partir','Danger '+z+'/100',function(){var p=game.player;p.travel={from:p.island,destination:d,remaining:mo,danger:z};p.situation='Navigation';p.activity='Navigation';tl('Départ en mer','Cap sur '+d+'.','major')}],['Rester','Annuler.',function(){}]])}
function travel(m){var p=game.player,t=p.travel;t.remaining-=m;if(R('t')<.18)fight(t.danger*.75,'Incident en mer');if(!game.alive)return;if(t.remaining<=0){p.island=t.destination;p.region=inf(t.destination).region;p.travel=null;p.situation='Arrivée';p.activity='Explorer';if(p.visited.indexOf(p.island)<0)p.visited.push(p.island);if(game.codex.places.indexOf(p.island)<0)game.codex.places.push(p.island);tl('Nouvelle destination','Tu arrives à '+p.island+'.','major')}}
function world(m){var w=game.world,p=game.player;w.month+=m;while(w.month>=12){w.month-=12;w.year++;if(R('w')<.5)news('Mouvements de factions',pk(['La Marine redéploie des bâtiments.','Un nouvel équipage gagne en réputation.','Des agents révolutionnaires sont signalés.'],'w'))}var rp=w.pressures[p.region];Object.keys(rp).forEach(function(k){rp[k]=cl(rp[k]+(R('w')-.5)*m*2,0,100)});w.canon.forEach(function(c){if(c[2]==='future'&&w.year>=c[1]){c[2]=w.divergence>70&&R('w')<.4?'modified':'completed';tl(c[0],c[2]==='modified'?'Le monde diverge fortement.':'Un événement historique a lieu.','canon')}})}
function event(m){if(R('e')>.18+m*.02)return;var p=game.player,x=pk(['relation','money','danger','meet','haki','fruit'],'e');if(x==='relation'){var n=pk(['Mira','Doran','Seline','Rook','Nessa','Toma'],'r'),r={name:n,role:pk(['ami','rival','mentor','collègue'],'r'),affection:30+R('r')*50,respect:25+R('r')*55,trust:20+R('r')*55};game.relations.push(r);tl('Nouvelle rencontre',n+' devient '+r.role+'.','major')}else if(x==='money'){var z=1000+Math.floor(R('e')*12000);p.money+=z;tl('Bonne affaire','Tu gagnes '+z.toLocaleString('fr-FR')+' B.')}else if(x==='danger')fight(inf().danger+10+R('e')*35,'Confrontation imprévue');else if(x==='meet'){var a=CH.filter(function(c){return c[2]===p.region});if(a.length){var c=pk(a,'e');if(game.codex.people.indexOf(c[0])<0)game.codex.people.push(c[0]);tl('Rencontre canonique','Tu croises '+c[0]+' ('+c[1]+').','canon')}}else if(x==='haki'){var k=pk(['Observation','Armement','Conquérant'],'h');if(p.latent[k]>55&&p.haki[k]===0){p.haki[k]=1;syncPowers();tl('Éveil du Haki','Ton Haki de '+k+' s’éveille.','major')}else if(p.haki[k]){trainHaki(k,.6);syncPowers();tl('Instinct affûté','Ton Haki de '+k+' progresse légèrement.')}}else if(x==='fruit'&&!p.fruit&&!p.heldFruit&&R('e')<.32){var av=game.world.fruits.filter(function(n){return !game.world.fruitRegistry[n]||game.world.fruitRegistry[n].status==='available'});if(av.length){var fr=pk(av,'e');decision('Un Fruit du démon','Tu découvres '+fr+'. Rien ne t’oblige à le consommer.',[['Le manger','Obtenir son pouvoir, mais perdre la capacité de nager.',function(){p.fruit=fr;p.fruitMastery=1;game.world.fruitRegistry[fr]={status:'consumed',holder:p.name};if(game.codex.fruits.indexOf(fr)<0)game.codex.fruits.push(fr);tl('Fruit du démon','Tu consommes le '+fr+'.','major')}],['Le conserver','Le garder pour plus tard.',function(){p.heldFruit=fr;game.world.fruitRegistry[fr]={status:'held',holder:p.name};tl('Fruit découvert','Tu conserves le '+fr+'.','major')}],['Le vendre','Transformer cette rareté en Berry.',function(){var val=40000+Math.round(R('fruit')*110000);p.money+=val;game.world.fruitRegistry[fr]={status:'sold',holder:null};tl('Vente exceptionnelle','Tu vends le '+fr+' pour '+val.toLocaleString('fr-FR')+' B.','major')}]])}}}
function die(c){game.alive=false;game.death={cause:c};game.player.health=0;tl('Mort',c,'danger')}
function advance(){if(!game||!game.alive||game.pending)return;var p=game.player,m=p.ageMonths<72?6:p.ageMonths<180?3:game.mission?Math.min(1,game.mission.remaining):p.travel?Math.min(1,p.travel.remaining):1+R('time')*2;m=Math.max(.5,Math.round(m*2)/2);p.ageMonths+=m;world(m);p.health=cl(p.health+m*2,0,100);p.energy=cl(p.energy+m*4,0,100);p.conditions.forEach(function(c){c.months-=m});p.conditions=p.conditions.filter(function(c){return c.months>0});careerTick(m);if(p.travel)travel(m);else if(game.mission){game.mission.remaining-=m;train(m);if(game.mission.remaining<=0)resolveMission()}else{train(m);event(m)}if(!game.alive){save();render();deathModal();return}if(p.ageMonths>=72&&p.situation==='Enfance'){p.situation='Formation';p.activity='Études';tl('Formation','Tu commences une formation structurée.','major')}if(p.ageMonths>=180&&p.career==='Aucune'&&!game.pending)career();p.danger=p.conditions.length?'Moyen':inf().danger>45?'Élevé':inf().danger>20?'Moyen':'Faible';save();render()}
function rep(){var r=game.player.reputation;return r>75?'Célèbre':r>40?'Reconnu':r>15?'Connu':'Inconnu'}
function slots(){var b=$('#saveSlots');b.innerHTML='';for(var i=1;i<=3;i++){(function(i){var s=load(i),x=document.createElement('button');x.className='save-slot'+(s?'':' empty');x.innerHTML=s?'<strong>'+e(s.player.name)+'</strong><small>'+Math.floor(s.player.ageMonths/12)+' ans • '+e(s.player.faction)+'<br>'+e(s.player.island)+'</small>':'<strong>＋ Nouvelle vie</strong><small>Emplacement '+i+'</small>';x.onclick=function(){slot=i;if(s){game=s;render()}else $('#creationCard').classList.remove('hidden')};b.appendChild(x)})(i)}}
function bar(o){return Object.keys(o).map(function(k){var v=o[k];return '<div class="stat-row"><span>'+e(k)+'</span><div class="stat-bar"><div class="stat-fill" style="width:'+cl(v,0,100)+'%"></div></div><span class="stat-value">'+Math.round(v)+'</span></div>'}).join('')}
function showGame(){$('#startScreen').classList.remove('active');$('#gameScreen').classList.add('active');$('#bottomNav').classList.remove('hidden');$('#homeBtn').classList.remove('hidden')}
function showStart(){game=null;$('#gameScreen').classList.remove('active');$('#startScreen').classList.add('active');$('#bottomNav').classList.add('hidden');$('#homeBtn').classList.add('hidden');slots()}
function renderTimeline(){var a=game.timeline.filter(function(x){return !majorOnly||['major','danger','canon'].indexOf(x.type)>=0});$('#timeline').innerHTML=a.slice(0,45).map(function(x){return '<div class="timeline-item '+e(x.type)+'"><span class="timeline-dot"></span><span class="timeline-age">'+e(x.age)+'</span><div class="timeline-title">'+e(x.title)+'</div><div class="timeline-desc">'+e(x.desc)+'</div></div>'}).join('')}
function renderChar(){var p=game.player,rec=careerRecord(),cfg=CAREERS[p.faction]||CAREERS.Civil,repv=p.factionRep[p.faction]||0,next=nextRank(),ri=rankIndex(),sal=salaryPerMonth();
 $('#identityGrid').innerHTML=[['Nom',p.name],['Origine',p.origin],['Race',p.race],['Lieu',p.island],['Faction',cfg.label],['Réputation',rep()]].map(function(x){return '<div class="info-cell"><span>'+e(x[0])+'</span><strong>'+e(x[1])+'</strong></div>'}).join('');
 $('#careerStandingBadge').textContent=standingLabel(repv);$('#careerCard').innerHTML='<strong>'+e(cfg.label)+' • '+e(p.rank)+'</strong><p>'+(p.specialization?'Spécialisation : '+e(p.specialization)+' • ':'')+'Ancienneté : '+Math.floor(rec.months)+' mois • Missions : '+rec.successes+' réussies / '+rec.failures+' échouées</p>'+(sal?'<span class="salary-chip">'+sal.toLocaleString('fr-FR')+' B / mois</span>':'<span class="salary-chip">Revenus à la mission</span>');
 if(next){var xpPct=cl(rec.xp/next.xp*100,0,100),reqs=[['XP '+Math.round(rec.xp)+' / '+next.xp,rec.xp>=next.xp],['Réputation '+Math.round(repv)+' / '+next.rep,repv>=next.rep],['Puissance '+Math.round(power())+' / '+next.pow,power()>=next.pow]];$('#careerProgressCard').innerHTML='<div class="career-progress-head"><strong>Prochain rang : '+e(next.n)+'</strong><span>'+Math.round(xpPct)+'%</span></div><div class="career-progress-bar"><div style="width:'+xpPct+'%"></div></div><div class="career-reqs">'+reqs.map(function(r){return '<span class="'+(r[1]?'met':'unmet')+'">'+e(r[0])+'</span>'}).join('')+'</div>'}else $('#careerProgressCard').innerHTML='<div class="career-progress-head"><strong>Rang maximal automatique atteint</strong><span>Les postes supérieurs dépendent d’événements du monde.</span></div>';
 $('#specializationBadge').textContent=p.specialization||'À choisir';$('#specializationCard').innerHTML=p.specialization?'<strong>'+e(p.specialization)+'</strong><p>Cette spécialisation influence tes missions et ta progression secondaire.</p>':'<strong>Aucune spécialisation</strong><p>Choisir un rôle ouvre des missions spécifiques. Une réorientation ultérieure coûte 10% d’XP carrière.</p>';
 $('#specializationOptions').innerHTML=cfg.specs.map(function(sp){var q=specEligibility(sp),sel=p.specialization===sp;return '<button class="action-card '+(sel?'selected ':'')+(q[0]?'':'locked')+'" data-sp="'+e(sp)+'"><strong>'+e(sp)+'</strong><small>'+(sel?'Spécialisation actuelle':q[0]?'Choisir cette voie':e(q[1]))+'</small></button>'}).join('');$$('[data-sp]').forEach(function(b){b.onclick=function(){chooseSpecialization(b.dataset.sp)}});
 $('#factionStanding').innerHTML=FACTION_KEYS.map(function(f){var v=p.factionRep[f]||0,pos=cl((v+100)/2,0,100);return '<div class="standing-row"><div class="standing-head"><strong>'+e(CAREERS[f]?CAREERS[f].label:f)+'</strong><span>'+standingLabel(v)+' • '+Math.round(v)+'</span></div><div class="standing-meter"><div class="standing-marker" style="left:'+pos+'%"></div></div></div>'}).join('');
 $('#careerActions').innerHTML='<button id="changeCareerBtn" class="action-card career-action-warning"><strong>Changer de voie</strong><small>Quitter ta faction peut avoir des conséquences durables.</small></button><button id="careerRecordBtn" class="action-card"><strong>Dossier de carrière</strong><small>'+p.careerHistory.length+' changement(s) de voie • '+Math.round(p.salaryTotal).toLocaleString('fr-FR')+' B de salaire cumulés</small></button>';$('#changeCareerBtn').onclick=careerChangeDecision;$('#careerRecordBtn').onclick=function(){toast('XP carrière : '+Math.round(rec.xp)+' • ancienneté : '+Math.floor(rec.months)+' mois')};
 $('#ambitionCard').innerHTML='<strong>'+e(p.ambition)+'</strong><p>Orientation personnelle.</p>';var aa=['Survivre','Devenir puissant','Explorer le monde','Faire fortune','Entrer dans l’histoire'];$('#ambitionOptions').innerHTML=aa.map(function(a){return '<button class="action-card '+(p.ambition===a?'active':'')+'" data-a="'+e(a)+'"><strong>'+e(a)+'</strong></button>'}).join('');$$('[data-a]').forEach(function(b){b.onclick=function(){p.ambition=b.dataset.a;save();renderChar()}});
 $('#missionBoard').innerHTML=game.mission?'<div class="mission-card active-mission"><strong>'+e(game.mission.title)+'</strong><p>'+game.mission.remaining.toFixed(1)+' mois restants • '+game.mission.xp+' XP carrière</p></div>':board().map(function(m){return '<button class="mission-card" data-m="'+m.id+'"><strong>'+e(m.title)+'</strong><p>Danger '+m.danger+' • '+m.reward.toLocaleString('fr-FR')+' B • '+m.xp+' XP</p>'+(m.spec?'<small>Spécialisation : '+e(m.spec)+'</small>':'')+'</button>'}).join('');$$('[data-m]').forEach(function(b){b.onclick=function(){startMission(+b.dataset.m)}});
 var acts=['Études','Entraînement','Navigation','Sabre','Médecine',activityForFaction(p.faction)];if(p.haki.Observation)acts.push('Haki Observation');if(p.haki.Armement)acts.push('Haki Armement');if(p.haki.Conquérant)acts.push('Haki Conquérant');if(p.fruit)acts.push('Maîtrise du Fruit');acts=acts.filter(function(v,i,a){return a.indexOf(v)===i});$('#activityOptions').innerHTML=acts.map(function(a){return '<button class="action-card '+(p.activity===a?'active':'')+'" data-act="'+e(a)+'"><strong>'+e(a)+'</strong></button>'}).join('');$$('[data-act]').forEach(function(b){b.onclick=function(){p.activity=b.dataset.act;save();renderChar()}});
 $('#crewSection').classList.toggle('hidden',p.faction!=='Pirates');if(p.faction==='Pirates'){$('#crewName').textContent=p.rank.indexOf('Capitaine')>=0?'Ton équipage':'Équipage pirate';$('#crewMorale').textContent='Moral '+Math.round(cl(50+repv/3,15,95))+'%';$('#crewDetails').innerHTML='<div class="career-card"><p>'+(p.rank.indexOf('Capitaine')>=0?'Tu disposes désormais de l’autorité nécessaire pour développer ton propre équipage.':'Ta place dépend encore de ta réputation et de tes résultats.')+'</p></div>'}
 $('#equipmentList').innerHTML=['Tenue de voyage',p.style,p.fruit||'Aucun Fruit'].map(function(x){return '<span class="chip">'+e(x)+'</span>'}).join('');$('#storageStatus').textContent='Autosave local'
}
function renderAb(){var p=game.player;$('#powerEstimate').textContent='Puissance ~'+Math.round(power())+' • '+powerRank();$('#statsList').innerHTML=bar(p.stats);$('#skillsList').innerHTML=bar(p.skills);$('#hakiList').innerHTML=Object.keys(p.haki).map(function(k){return '<div class="ability-row"><strong>'+e(k)+'</strong><span>'+(p.haki[k]?'Niveau '+Math.round(p.haki[k]):'Non éveillé')+'</span></div>'}).join('');$('#fruitCard').innerHTML=p.fruit?'<strong>'+e(p.fruit)+'</strong><div class="mastery-meter"><div style="width:'+p.fruitMastery+'%"></div></div><span>Maîtrise '+Math.round(p.fruitMastery)+'%</span>':p.heldFruit?'<strong>'+e(p.heldFruit)+'</strong><p>Fruit conservé, non consommé.</p>':'Aucun Fruit consommé.';
 var all=[].concat.apply([],Object.keys(TECH).map(function(k){return TECH[k]})),prof=TECH[p.style]||TECH['Équilibré'];$('#techniqueCount').textContent=(p.techniques||[]).length+' maîtrisées';$('#techniqueList').innerHTML=prof.map(function(t){var ok=p.techniques.indexOf(t.id)>=0,m=p.techniqueMastery[t.id]||0;return '<div class="technique-card '+(ok?'':'locked')+'"><strong>'+e(t.name)+'</strong><span>'+(ok?'Maîtrise '+Math.round(m)+'%':'Requiert '+e(t.skill)+' '+t.req)+'</span><small>Bonus de combat '+t.bonus+'</small></div>'}).join('')+(p.fruit&&p.fruitMastery>=20?'<div class="technique-card"><strong>Application du '+e(p.fruit)+'</strong><span>Maîtrise '+Math.round(p.fruitMastery)+'%</span><small>'+(p.fruitAwakened?'Éveil acquis':'Le pouvoir évolue avec la pratique réelle.')+'</small></div>':'');
 $('#hakiApplications').innerHTML=Object.keys(p.hakiApplications).map(function(k){var a=p.hakiApplications[k];return '<div class="haki-app"><strong>'+e(k)+'</strong><small>'+(a.length?e(a.join(' • ')):'Aucune application connue')+'</small></div>'}).join('');
 $('#fruitMasteryCard').innerHTML=p.fruit?'<strong>'+e(p.fruit)+'</strong><div class="mastery-meter"><div style="width:'+p.fruitMastery+'%"></div></div><p>'+Math.round(p.fruitMastery)+'% de maîtrise'+(p.fruitAwakened?' • ÉVEIL':'')+'.</p>':p.heldFruit?'<strong>'+e(p.heldFruit)+'</strong><p>Tu le conserves sans l’avoir mangé.</p><button id="eatHeldFruit" class="primary-btn small">Le consommer</button>':'<strong>Aucun pouvoir</strong><p>Les Fruits existent physiquement dans le monde et doivent être trouvés.</p>';
 var eat=$('#eatHeldFruit');if(eat)eat.onclick=function(){var fr=p.heldFruit;p.heldFruit=null;p.fruit=fr;p.fruitMastery=1;game.world.fruitRegistry[fr]={status:'consumed',holder:p.name};tl('Fruit du démon','Tu décides finalement de consommer le '+fr+'.','major');save();renderAb()};
 $('#combatStyleCard').innerHTML='<strong>'+e(p.style)+'</strong><p>Combat '+Math.round(p.skills.Combat)+' • Sabre '+Math.round(p.skills.Sabre)+' • Tir '+Math.round(p.skills.Tir)+'</p><span class="power-rank">'+powerRank()+'</span>';$('#combatActions').innerHTML='<button id="challengeBtn" class="action-card"><strong>Défi local</strong><small>Affronter un adversaire cohérent avec la zone actuelle.</small></button><button id="martialTrainBtn" class="action-card"><strong>Priorité combat</strong><small>Passer l’activité principale à Entraînement.</small></button>';$('#challengeBtn').onclick=challengeFight;$('#martialTrainBtn').onclick=function(){p.activity='Entraînement';save();renderChar();toast('Activité : Entraînement')};
 if(game.lastCombat){$('#combatReportSection').classList.remove('hidden');var c=game.lastCombat,o=$('#combatOutcome');o.textContent=c.outcome;o.className='badge '+(c.outcome.indexOf('Victoire')>=0?'outcome-win':'outcome-loss');$('#combatReport').innerHTML='<div><span>Puissance</span><strong>'+c.playerPower+' vs '+c.opponentPower+'</strong></div><div><span>Styles</span><strong>'+e(c.playerStyle)+' vs '+e(c.opponentStyle)+'</strong></div><div><span>Terrain</span><strong>'+e(c.terrain)+'</strong></div><div><span>Chance estimée</span><strong>'+c.chance+'%</strong></div><div class="combat-log">'+e(c.log)+'</div>'}else $('#combatReportSection').classList.add('hidden')}
function renderRel(){$('#relationsList').innerHTML=game.relations.length?game.relations.map(function(r){return '<div class="relation-card"><div class="relation-avatar">'+e(r.name[0])+'</div><div class="relation-copy"><strong>'+e(r.name)+'</strong><span>'+e(r.role)+' • confiance '+Math.round(r.trust)+'%</span></div></div>'}).join(''):'<p class="helper-text">Aucune relation importante.</p>'}
function renderWorld(){var p=game.player,w=game.world,q=inf(),rp=w.pressures[p.region];$('#worldHeadline').textContent='Grande Ère de la Piraterie';$('#worldSubhead').textContent='Année '+w.year+', mois '+(Math.floor(w.month)+1)+'.';$('#worldMeta').innerHTML='<span>Divergence '+Math.round(w.divergence)+'%</span><span>'+p.visited.length+' lieux visités</span>';$('#placeName').textContent=p.travel?'En mer → '+p.travel.destination:p.island;$('#placeDanger').textContent='Danger '+q.danger;$('#placeDescription').textContent=p.travel?'Temps restant : '+Math.max(0,p.travel.remaining).toFixed(1)+' mois.':'Région : '+p.region;$('#placeTags').innerHTML='<span class="chip">'+e(p.region)+'</span>';$('#travelStatus').textContent=p.travel?'Traversée':p.region;$('#travelOptions').innerHTML=p.travel?'<div class="career-card"><p>Utilise AVANCER pour poursuivre.</p></div>':q.routes.map(function(d){var z=req(d);return '<button class="action-card '+(z[0]?'':'locked')+'" data-d="'+e(d)+'"><strong>'+e(d)+'</strong><small>'+e(inf(d).region)+' • danger '+inf(d).danger+(z[0]?'':' • '+z[1])+'</small></button>'}).join('');$$('[data-d]').forEach(function(b){b.onclick=function(){go(b.dataset.d)}});$('#regionMap').innerHTML=REG.map(function(r){var v=p.visited.filter(function(x){return inf(x).region===r}).length,t=Object.keys(PL).filter(function(x){return inf(x).region===r}).length;return '<div class="region-card '+(r===p.region?'active':'')+'"><strong>'+e(r)+'</strong><span>'+v+'/'+t+' lieux</span></div>'}).join('');var ac=CH.filter(function(c){return c[2]===p.region});$('#localActors').innerHTML=ac.length?ac.map(function(c){return '<div class="actor-row"><strong>'+e(c[0])+'</strong><span>'+e(c[1])+' • importance '+c[3]+'</span></div>'}).join(''):'<p class="helper-text">Aucun acteur majeur identifié.</p>';$('#factionOverview').innerHTML=Object.keys(w.factions).map(function(n){return '<div class="faction-card"><strong>'+e(n)+'</strong><span>Puissance '+Math.round(w.factions[n])+'</span></div>'}).join('');$('#regionTitle').textContent=p.region;$('#pressureBars').innerHTML=bar(rp);$('#worldNews').innerHTML=game.news.map(function(n){return '<div class="news-item"><strong>'+e(n.title)+'</strong><span>'+e(n.desc)+'</span></div>'}).join('');$('#divergenceBadge').textContent='Divergence '+Math.round(w.divergence)+'%';$('#canonList').innerHTML=w.canon.map(function(c){return '<div class="canon-item"><span class="status">'+e(c[2])+'</span><strong>'+e(c[0])+'</strong><span>Année '+c[1]+' • résistance '+c[3]+'</span></div>'}).join('');var co=[].concat(game.codex.people,game.codex.places,game.codex.factions,game.codex.fruits).filter(function(v,i,a){return a.indexOf(v)===i});$('#codexList').innerHTML=co.map(function(x){return '<span class="chip">'+e(x)+'</span>'}).join('')}
function render(){if(!game)return;showGame();var p=game.player;$('#ageLabel').textContent=age();$('#locationLabel').textContent=p.travel?'→ '+p.travel.destination:p.island;$('#moneyLabel').textContent=Math.floor(p.money).toLocaleString('fr-FR')+' B';$('#playerName').textContent=p.name;$('#avatarInitial').textContent=p.name.charAt(0).toUpperCase();$('#playerSubtitle').textContent=p.race+' • '+p.region+' • '+p.faction;$('#lifeStatus').textContent=p.situation;$('#repPill').textContent=rep();$('#situationTitle').textContent=p.situation;$('#activityValue').textContent=p.activity;$('#factionValue').textContent=p.faction;$('#healthValue').textContent=Math.round(p.health)+'%';$('#energyValue').textContent=Math.round(p.energy)+'%';var d=$('#dangerBadge');d.textContent=p.danger;d.className='danger-badge '+(p.danger==='Élevé'?'high':p.danger==='Moyen'?'medium':'low');$('#conditionChips').innerHTML=p.conditions.length?p.conditions.map(function(c){return '<span class="chip">'+e(c.name)+'</span>'}).join(''):'<span class="chip">Aucune blessure</span>';$('#advanceBtn').disabled=!game.alive||!!game.pending;$('#advanceHint').textContent=game.pending?'Une décision t’attend':game.mission?'Mission : '+game.mission.title:p.travel?'Navigation en cours':'Le moteur choisit la durée adaptée';if(game.pending){$('#attentionCard').classList.remove('hidden');$('#attentionTitle').textContent=game.pending.title;$('#attentionText').textContent=game.pending.text}else $('#attentionCard').classList.add('hidden');renderTimeline();renderChar();renderAb();renderRel();renderWorld();$('#devOutput').textContent=JSON.stringify({seed:game.seed,power:power(),player:p,world:game.world},null,2)}
function deathModal(){var p=game.player;$('#deathTitle').textContent=p.name+', '+age();$('#deathSummary').innerHTML='<div><span>Cause</span><strong>'+e(game.death.cause)+'</strong></div><div><span>Carrière</span><strong>'+e(p.career)+'</strong></div><div><span>Victoires</span><strong>'+p.wins+'</strong></div><div><span>Lieux</span><strong>'+p.visited.length+'</strong></div>';$('#deathModal').classList.remove('hidden')}
function toast(m){var t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(t._t);t._t=setTimeout(function(){t.classList.add('hidden')},1600)}
function backup(m){backupMode=m;$('#backupModal').classList.remove('hidden');$('#backupTitle').textContent=m==='export'?'Exporter':'Importer';$('#backupText').value=m==='export'?btoa(unescape(encodeURIComponent(JSON.stringify(game)))):'';$('#backupPrimaryBtn').textContent=m==='export'?'Copier':'Importer'}
function bind(){
 $$('.mode-card').forEach(function(b){b.onclick=function(){mode=b.dataset.mode;$$('.mode-card').forEach(function(x){x.classList.toggle('selected',x===b)});$('#customFields').classList.toggle('hidden',mode!=='custom')}});
 $('#newLifeBtn').onclick=function(){make();$('#creationCard').classList.add('hidden');render()};$('#cancelCreate').onclick=function(){$('#creationCard').classList.add('hidden')};$('#advanceBtn').onclick=advance;$('#attentionBtn').onclick=showDecision;$('#homeBtn').onclick=showStart;
 $('#deathHomeBtn').onclick=function(){$('#deathModal').classList.add('hidden');showStart()};$('#deathNewBtn').onclick=function(){localStorage.removeItem(key());$('#deathModal').classList.add('hidden');showStart();$('#creationCard').classList.remove('hidden')};
 $('#timelineFilter').onclick=function(){majorOnly=!majorOnly;renderTimeline()};$$('.nav-item').forEach(function(b){b.onclick=function(){$$('.nav-item').forEach(function(x){x.classList.toggle('active',x===b)});$$('.tab-panel').forEach(function(x){x.classList.toggle('active',x.dataset.panel===b.dataset.tab)});scrollTo(0,0)}});
 $('#devToggle').onclick=function(){if(game)$('#developerPanel').classList.remove('hidden')};$('#closeDev').onclick=function(){$('#developerPanel').classList.add('hidden')};$('#exportSaveBtn').onclick=function(){backup('export')};$('#importSaveBtn').onclick=function(){backup('import')};$('#backupCloseBtn').onclick=function(){$('#backupModal').classList.add('hidden')};
 $('#backupPrimaryBtn').onclick=function(){if(backupMode==='export'){if(navigator.clipboard)navigator.clipboard.writeText($('#backupText').value);toast('Sauvegarde copiée ou prête à copier.')}else try{game=migrate(JSON.parse(decodeURIComponent(escape(atob($('#backupText').value.trim())))));save();$('#backupModal').classList.add('hidden');render()}catch(x){toast('Sauvegarde invalide.')}};
 document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')save()});window.addEventListener('pagehide',save)
}
function init(){bind();if(location.protocol!=='file:')$('#localFileWarning').classList.add('hidden');if(/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.matchMedia('(display-mode: standalone)').matches&&location.protocol==='https:')$('#iosInstallCard').classList.remove('hidden');slots();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(function(){})}
init();
})();