(function(){
'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
var game=null,slot=1,mode='destiny',majorOnly=false,backupMode='export',P='opl-v05-';
var ORIG=['East Blue','North Blue','West Blue','South Blue'],REG=ORIG.concat(['Grand Line','New World']);
var ST=['Force','Vitesse','Agilité','Endurance','Résistance','Réflexes','Discipline','Volonté'];
var SK=['Combat','Sabre','Tir','Navigation','Médecine','Commandement','Discrétion','Science'];
var PL={
'Loguetown':['East Blue',14,['Shells Town','Baratie','Reverse Mountain']],
'Shells Town':['East Blue',8,['Loguetown','Orange Town']],
'Orange Town':['East Blue',9,['Shells Town','Syrup Village']],
'Goa':['East Blue',10,['Shimotsuki','Syrup Village']],
'Shimotsuki':['East Blue',6,['Goa','Baratie']],
'Syrup Village':['East Blue',5,['Orange Town','Goa','Baratie']],
'Baratie':['East Blue',12,['Loguetown','Shimotsuki','Syrup Village']],
'Lvneel':['North Blue',12,['Flevance','Minion Island']],
'Flevance':['North Blue',20,['Lvneel','Minion Island']],
'Minion Island':['North Blue',22,['Flevance','Reverse Mountain']],
'Ohara':['West Blue',8,['Ilusia']],
'Ilusia':['West Blue',14,['Ohara','Reverse Mountain']],
'Baterilla':['South Blue',10,['Torino','Reverse Mountain']],
'Torino':['South Blue',16,['Baterilla']],
'Reverse Mountain':['Grand Line',32,['Loguetown','Minion Island','Ilusia','Baterilla','Twin Cape']],
'Twin Cape':['Grand Line',28,['Reverse Mountain','Whisky Peak']],
'Whisky Peak':['Grand Line',34,['Twin Cape','Little Garden']],
'Little Garden':['Grand Line',39,['Whisky Peak','Drum']],
'Drum':['Grand Line',32,['Little Garden','Alabasta']],
'Alabasta':['Grand Line',37,['Drum','Jaya']],
'Jaya':['Grand Line',43,['Alabasta','Water 7']],
'Water 7':['Grand Line',29,['Jaya','Thriller Bark']],
'Thriller Bark':['Grand Line',48,['Water 7','Sabaody']],
'Sabaody':['Grand Line',45,['Thriller Bark','Fish-Man Island']],
'Fish-Man Island':['Grand Line',44,['Sabaody','Punk Hazard']],
'Punk Hazard':['New World',66,['Fish-Man Island','Dressrosa']],
'Dressrosa':['New World',61,['Punk Hazard','Zou','Whole Cake Island']],
'Zou':['New World',52,['Dressrosa','Wano']],
'Whole Cake Island':['New World',78,['Dressrosa','Wano']],
'Wano':['New World',82,['Zou','Whole Cake Island','Egghead']],
'Egghead':['New World',68,['Wano']]};
var CH=[['Garp','Marine','East Blue',90],['Shanks','Pirates','East Blue',95],['Rayleigh','Pirates','Grand Line',92],['Mihawk','Indépendant','Grand Line',90],['Dragon','Révolutionnaires','Grand Line',98],['Kaido','Pirates','New World',99],['Big Mom','Pirates','New World',99],['Barbe Blanche','Pirates','New World',100]];
var MS={Civil:[['Livraison côtière',18,6500],['Escorte commerciale',28,12000]],Marine:[['Patrouille portuaire',20,9000],['Contrebandiers',38,18000]],Pirates:[['Piller un convoi',42,22000],['Équipage rival',55,33000]],'Chasseur de primes':[['Traquer un hors-la-loi',35,18000],['Capturer un capitaine',52,30000]],Révolutionnaires:[['Acheminer des renseignements',30,0],['Saboter une installation',58,0]],Gouvernement:[['Surveillance discrète',25,10000],['Opération Cipher Pol',64,42000]]};
function e(s){return String(s==null?'':s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function cl(n,a,b){return Math.max(a,Math.min(b,n))}
function H(s){var x=2166136261>>>0;String(s).split('').forEach(function(c){x=Math.imul(x^c.charCodeAt(0),16777619)});return x>>>0}
function R(k){k=k||'m';var c=game?(game.rng[k]||0):0,s=(game?game.seed:1)^H(k+':'+c);if(game)game.rng[k]=c+1;var t=s+0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}
function pk(a,k){return a[Math.floor(R(k)*a.length)]}
function inf(n){var p=PL[n||game.player.island]||[game.player.region,10,[]];return{region:p[0],danger:p[1],routes:p[2]}}
function age(){var m=game.player.ageMonths,y=Math.floor(m/12),o=Math.floor(m%12);return y?(y+' an'+(y>1?'s':'')+(o?' et '+o+' mois':'')):(o+' mois')}
function key(){return P+slot}function save(){if(game)localStorage.setItem(key(),JSON.stringify(game))}function load(i){try{return JSON.parse(localStorage.getItem(P+i)||'null')}catch(x){return null}}
function tl(t,d,y){game.timeline.unshift({age:age(),title:t,desc:d,type:y||''});game.timeline=game.timeline.slice(0,100)}
function news(t,d){game.news.unshift({title:t,desc:d});game.news=game.news.slice(0,25)}
function press(){var o={};REG.forEach(function(r){o[r]={Piraterie:20+R('w')*25,Marine:30+R('w')*35,Criminalité:15+R('w')*30,Révolution:5+R('w')*20,Prospérité:40+R('w')*35,Instabilité:10+R('w')*25}});return o}
function make(){
 var seed=Number($('#seedInput').value)||Math.floor(Math.random()*2147483647),origin=mode==='custom'?$('#originInput').value:pk(ORIG,'b');
 game={version:5,seed:seed,rng:{},alive:true,pending:null,mission:null,timeline:[],news:[],relations:[],codex:{people:[],places:[],factions:['Civil'],fruits:[]},world:{year:0,month:0,divergence:0,pressures:{},factions:{Marine:82,Pirates:79,Révolutionnaires:56,Gouvernement:94},canon:[['Exécution de Gol D. Roger',0,'completed',100],['Nouvelle génération',18,'future',75],['Guerre au sommet',22,'future',95]],fruits:['Mera Mera no Mi','Ope Ope no Mi','Hie Hie no Mi','Moku Moku no Mi']},player:{name:$('#nameInput').value.trim()||'Kael Maren',difficulty:$('#difficultyInput').value,ageMonths:0,race:mode==='custom'?$('#raceInput').value:pk(['Humain','Humain','Humain','Mink','Homme-poisson'],'b'),origin:origin,region:origin,island:'',situation:'Enfance',activity:'Grandir',faction:'Civil',career:'Aucune',rank:'Enfant',money:3000,health:100,energy:100,danger:'Faible',conditions:[],bounty:0,highestBounty:0,reputation:0,ambition:'Survivre',wins:0,losses:0,travel:null,visited:[],style:mode==='custom'?$('#styleInput').value:pk(['Équilibré','Corps-à-corps','Sabreur','Tireur'],'b'),fruit:null,haki:{Observation:0,Armement:0,Conquérant:0},latent:{Observation:20+R('h')*60,Armement:20+R('h')*60,Conquérant:R('h')<.04?90:0},stats:{},skills:{},caps:{}}};
 var homes=Object.keys(PL).filter(function(n){return PL[n][0]===origin});game.player.island=pk(homes,'b');game.player.visited=[game.player.island];game.codex.places=[game.player.island];game.world.pressures=press();
 ST.forEach(function(k){game.player.stats[k]=8+R('b')*12;game.player.caps[k]=68+R('c')*25});SK.forEach(function(k){game.player.skills[k]=2+R('b')*8;game.player.caps[k]=68+R('c')*25});
 tl('Naissance','Tu nais à '+game.player.island+', dans '+origin+'.','major');news('Grande Ère de la Piraterie','Le monde entre dans une période de bouleversements.');save();return game}
function diff(){return game.player.difficulty==='Casual'?[1.2,.75]:game.player.difficulty==='Ironman'?[.9,1.55]:[1,1]}
function power(){var p=game.player,a=ST.reduce(function(s,k){return s+p.stats[k]},0)/ST.length,b=SK.reduce(function(s,k){return s+p.skills[k]},0)/SK.length;return a*.48+b*.42+(p.haki.Observation+p.haki.Armement+p.haki.Conquérant)*.23+(p.fruit?12:0)}
function gain(k,n){var p=game.player,b=p.stats[k]!=null?p.stats:p.skills,z=b[k],cap=p.caps[k]||90;if(z>=cap)return 0;var g=n*diff()[0]*cl(1-Math.pow(z/110,1.7),.12,1);b[k]=cl(z+g,0,cap);return g}
function train(m){var p=game.player,map={Grandir:['Endurance','Réflexes'],Études:['Discipline','Science'],Entraînement:['Force','Combat'],Navigation:['Navigation','Endurance'],Sabre:['Sabre','Réflexes'],'Formation Marine':['Discipline','Combat'],'Formation Pirates':['Combat','Navigation'],'Formation Révolutionnaires':['Discrétion','Commandement'],'Formation Gouvernement':['Discipline','Discrétion'],Médecine:['Médecine','Discipline']},ks=map[p.activity]||[pk(ST,'p'),pk(SK,'p')];ks.forEach(function(k){gain(k,m*(.5+R('p')*.8))})}
function decision(t,txt,ch){game.pending={title:t,text:txt,choices:ch};save();render();showDecision()}
function showDecision(){if(!game.pending)return;$('#decisionTitle').textContent=game.pending.title;$('#decisionText').textContent=game.pending.text;$('#decisionChoices').innerHTML=game.pending.choices.map(function(c,i){return '<button class="choice-btn" data-c="'+i+'"><strong>'+e(c[0])+'</strong><small>'+e(c[1])+'</small></button>'}).join('');$$('[data-c]').forEach(function(b){b.onclick=function(){var c=game.pending.choices[+b.dataset.c];c[2]();game.pending=null;$('#decisionModal').classList.add('hidden');save();render()}});$('#decisionModal').classList.remove('hidden')}
function join(f,r){var p=game.player;p.faction=f;p.career=f;p.rank=r;p.situation='Carrière';p.activity=f==='Civil'?'Études':'Formation '+f;if(game.codex.factions.indexOf(f)<0)game.codex.factions.push(f);tl('Nouvelle carrière','Tu rejoins '+f+'.','major')}
function career(){decision('Choisir une voie','Ta vie adulte commence.',[['Marine','Missions et promotions.',function(){join('Marine','Recrue')}],['Pirate','Liberté et prime.',function(){join('Pirates','Novice')}],['Chasseur de primes','Contrats indépendants.',function(){join('Chasseur de primes','Indépendant')}],['Civil','Commerce, médecine, science.',function(){join('Civil','Apprenti')}],['Révolutionnaires','Voie clandestine.',function(){join('Révolutionnaires','Sympathisant')}],['Gouvernement','Renseignement et Cipher Pol.',function(){join('Gouvernement','Agent junior')}]])}
function fight(d,t){var p=game.player,ok=R('f')<cl(.18+(power()/d)*.42,.04,.94);if(ok){p.wins++;p.reputation+=4;if(p.faction==='Pirates'){p.bounty+=Math.round(d*1200);p.highestBounty=Math.max(p.highestBounty,p.bounty)}gain('Combat',1+d/40);tl(t||'Combat','Tu remportes l’affrontement.','major');return true}p.losses++;var dmg=8+d*.35*R('f')*diff()[1];p.health-=dmg;tl(t||'Combat','Tu es battu et subis '+Math.round(dmg)+'% de dégâts.','danger');if(p.health<=0||R('f')<Math.max(0,(d-power())/250))die('Mort lors d’un affrontement.');else if(dmg>18)p.conditions.push({name:'Blessure',months:3});return false}
function board(){var a=MS[game.player.faction]||MS.Civil;return a.map(function(m,i){return{id:i,title:m[0],danger:Math.round(m[1]+inf().danger*.28),reward:m[2],months:1+Math.ceil(m[1]/25)}})}
function startMission(i){if(game.mission||game.player.ageMonths<168)return toast('Mission indisponible.');var m=board()[i];game.mission={title:m.title,danger:m.danger,reward:m.reward,remaining:m.months};game.player.situation='Mission';tl('Mission acceptée',m.title+'.','major');save();render()}
function resolveMission(){var m=game.mission,p=game.player,ok=fight(m.danger,'Mission : '+m.title);if(!game.alive)return;if(ok){p.money+=m.reward;p.reputation+=6;tl('Mission accomplie',m.title+' est terminée avec succès.','major')}else tl('Mission échouée',m.title+' échoue.','danger');game.mission=null;p.situation='Carrière'}
function req(d){var r=inf(d).region,p=game.player;if(r==='Grand Line'&&p.skills.Navigation<18)return[false,'Navigation 18'];if(r==='New World'&&(p.skills.Navigation<35||power()<35))return[false,'Navigation 35 + puissance 35'];return[true,'']}
function go(d){var q=req(d);if(!q[0])return toast('Accès verrouillé : '+q[1]);var z=inf(d).danger,mo=Math.max(.5,Math.round((.6+z/35+R('t')*.8)*10)/10);decision('Prendre la mer','Voyager vers '+d+' prendra environ '+mo+' mois.',[['Partir','Danger '+z+'/100',function(){var p=game.player;p.travel={from:p.island,destination:d,remaining:mo,danger:z};p.situation='Navigation';p.activity='Navigation';tl('Départ en mer','Cap sur '+d+'.','major')}],['Rester','Annuler.',function(){}]])}
function travel(m){var p=game.player,t=p.travel;t.remaining-=m;if(R('t')<.18)fight(t.danger*.75,'Incident en mer');if(!game.alive)return;if(t.remaining<=0){p.island=t.destination;p.region=inf(t.destination).region;p.travel=null;p.situation='Arrivée';p.activity='Explorer';if(p.visited.indexOf(p.island)<0)p.visited.push(p.island);if(game.codex.places.indexOf(p.island)<0)game.codex.places.push(p.island);tl('Nouvelle destination','Tu arrives à '+p.island+'.','major')}}
function world(m){var w=game.world,p=game.player;w.month+=m;while(w.month>=12){w.month-=12;w.year++;if(R('w')<.5)news('Mouvements de factions',pk(['La Marine redéploie des bâtiments.','Un nouvel équipage gagne en réputation.','Des agents révolutionnaires sont signalés.'],'w'))}var rp=w.pressures[p.region];Object.keys(rp).forEach(function(k){rp[k]=cl(rp[k]+(R('w')-.5)*m*2,0,100)});w.canon.forEach(function(c){if(c[2]==='future'&&w.year>=c[1]){c[2]=w.divergence>70&&R('w')<.4?'modified':'completed';tl(c[0],c[2]==='modified'?'Le monde diverge fortement.':'Un événement historique a lieu.','canon')}})}
function event(m){if(R('e')>.18+m*.02)return;var p=game.player,x=pk(['relation','money','danger','meet','haki','fruit'],'e');if(x==='relation'){var n=pk(['Mira','Doran','Seline','Rook','Nessa','Toma'],'r'),r={name:n,role:pk(['ami','rival','mentor','collègue'],'r'),affection:30+R('r')*50,respect:25+R('r')*55,trust:20+R('r')*55};game.relations.push(r);tl('Nouvelle rencontre',n+' devient '+r.role+'.','major')}else if(x==='money'){var z=1000+Math.floor(R('e')*12000);p.money+=z;tl('Bonne affaire','Tu gagnes '+z.toLocaleString('fr-FR')+' B.')}else if(x==='danger')fight(inf().danger+10+R('e')*35,'Confrontation imprévue');else if(x==='meet'){var a=CH.filter(function(c){return c[2]===p.region});if(a.length){var c=pk(a,'e');if(game.codex.people.indexOf(c[0])<0)game.codex.people.push(c[0]);tl('Rencontre canonique','Tu croises '+c[0]+' ('+c[1]+').','canon')}}else if(x==='haki'){var k=pk(['Observation','Armement','Conquérant'],'h');if(p.latent[k]>55&&p.haki[k]===0){p.haki[k]=1;tl('Éveil du Haki','Ton Haki de '+k+' s’éveille.','major')}}else if(x==='fruit'&&!p.fruit&&R('e')<.25){p.fruit=pk(game.world.fruits,'e');game.codex.fruits.push(p.fruit);tl('Fruit du démon','Tu consommes le '+p.fruit+'.','major')}}
function die(c){game.alive=false;game.death={cause:c};game.player.health=0;tl('Mort',c,'danger')}
function advance(){if(!game||!game.alive||game.pending)return;var p=game.player,m=p.ageMonths<72?6:p.ageMonths<180?3:game.mission?Math.min(1,game.mission.remaining):p.travel?Math.min(1,p.travel.remaining):1+R('time')*2;m=Math.max(.5,Math.round(m*2)/2);p.ageMonths+=m;world(m);p.health=cl(p.health+m*2,0,100);p.energy=cl(p.energy+m*4,0,100);p.conditions.forEach(function(c){c.months-=m});p.conditions=p.conditions.filter(function(c){return c.months>0});if(p.travel)travel(m);else if(game.mission){game.mission.remaining-=m;train(m);if(game.mission.remaining<=0)resolveMission()}else{train(m);event(m)}if(!game.alive){save();render();deathModal();return}if(p.ageMonths>=72&&p.situation==='Enfance'){p.situation='Formation';p.activity='Études';tl('Formation','Tu commences une formation structurée.','major')}if(p.ageMonths>=180&&p.career==='Aucune'&&!game.pending)career();p.danger=p.conditions.length?'Moyen':inf().danger>45?'Élevé':inf().danger>20?'Moyen':'Faible';save();render()}
function rep(){var r=game.player.reputation;return r>75?'Célèbre':r>40?'Reconnu':r>15?'Connu':'Inconnu'}
function slots(){var b=$('#saveSlots');b.innerHTML='';for(var i=1;i<=3;i++){(function(i){var s=load(i),x=document.createElement('button');x.className='save-slot'+(s?'':' empty');x.innerHTML=s?'<strong>'+e(s.player.name)+'</strong><small>'+Math.floor(s.player.ageMonths/12)+' ans • '+e(s.player.faction)+'<br>'+e(s.player.island)+'</small>':'<strong>＋ Nouvelle vie</strong><small>Emplacement '+i+'</small>';x.onclick=function(){slot=i;if(s){game=s;render()}else $('#creationCard').classList.remove('hidden')};b.appendChild(x)})(i)}}
function bar(o){return Object.keys(o).map(function(k){var v=o[k];return '<div class="stat-row"><span>'+e(k)+'</span><div class="stat-bar"><div class="stat-fill" style="width:'+cl(v,0,100)+'%"></div></div><span class="stat-value">'+Math.round(v)+'</span></div>'}).join('')}
function showGame(){$('#startScreen').classList.remove('active');$('#gameScreen').classList.add('active');$('#bottomNav').classList.remove('hidden');$('#homeBtn').classList.remove('hidden')}
function showStart(){game=null;$('#gameScreen').classList.remove('active');$('#startScreen').classList.add('active');$('#bottomNav').classList.add('hidden');$('#homeBtn').classList.add('hidden');slots()}
function renderTimeline(){var a=game.timeline.filter(function(x){return !majorOnly||['major','danger','canon'].indexOf(x.type)>=0});$('#timeline').innerHTML=a.slice(0,45).map(function(x){return '<div class="timeline-item '+e(x.type)+'"><span class="timeline-dot"></span><span class="timeline-age">'+e(x.age)+'</span><div class="timeline-title">'+e(x.title)+'</div><div class="timeline-desc">'+e(x.desc)+'</div></div>'}).join('')}
function renderChar(){var p=game.player;$('#identityGrid').innerHTML=[['Nom',p.name],['Origine',p.origin],['Race',p.race],['Lieu',p.island],['Faction',p.faction],['Réputation',rep()]].map(function(x){return '<div class="info-cell"><span>'+e(x[0])+'</span><strong>'+e(x[1])+'</strong></div>'}).join('');$('#careerCard').innerHTML='<strong>'+e(p.career)+'</strong><p>Rang : '+e(p.rank)+' • Prime : '+Math.floor(p.bounty).toLocaleString('fr-FR')+' B • Victoires : '+p.wins+'</p>';$('#ambitionCard').innerHTML='<strong>'+e(p.ambition)+'</strong><p>Orientation personnelle.</p>';var aa=['Survivre','Devenir puissant','Explorer le monde','Faire fortune','Entrer dans l’histoire'];$('#ambitionOptions').innerHTML=aa.map(function(a){return '<button class="action-card '+(p.ambition===a?'active':'')+'" data-a="'+e(a)+'"><strong>'+e(a)+'</strong></button>'}).join('');$$('[data-a]').forEach(function(b){b.onclick=function(){p.ambition=b.dataset.a;save();renderChar()}});$('#missionBoard').innerHTML=game.mission?'<div class="mission-card active-mission"><strong>'+e(game.mission.title)+'</strong><p>'+game.mission.remaining.toFixed(1)+' mois restants</p></div>':board().map(function(m){return '<button class="mission-card" data-m="'+m.id+'"><strong>'+e(m.title)+'</strong><p>Danger '+m.danger+' • '+m.reward.toLocaleString('fr-FR')+' B</p></button>'}).join('');$$('[data-m]').forEach(function(b){b.onclick=function(){startMission(+b.dataset.m)}});var acts=['Études','Entraînement','Navigation','Sabre','Médecine',p.faction==='Marine'?'Formation Marine':p.faction==='Pirates'?'Formation Pirates':p.faction==='Révolutionnaires'?'Formation Révolutionnaires':p.faction==='Gouvernement'?'Formation Gouvernement':'Explorer'];$('#activityOptions').innerHTML=acts.map(function(a){return '<button class="action-card '+(p.activity===a?'active':'')+'" data-act="'+e(a)+'"><strong>'+e(a)+'</strong></button>'}).join('');$$('[data-act]').forEach(function(b){b.onclick=function(){p.activity=b.dataset.act;save();renderChar()}});$('#crewSection').classList.toggle('hidden',p.faction!=='Pirates');if(p.faction==='Pirates'){$('#crewName').textContent='Équipage pirate';$('#crewMorale').textContent='Moral '+Math.round(55+p.reputation/3)+'%';$('#crewDetails').innerHTML='<div class="career-card"><p>Recrutements et pertes émergent pendant la carrière.</p></div>'}$('#equipmentList').innerHTML=['Tenue de voyage',p.style,p.fruit||'Aucun Fruit'].map(function(x){return '<span class="chip">'+e(x)+'</span>'}).join('');$('#storageStatus').textContent='Autosave local'}
function renderAb(){var p=game.player;$('#powerEstimate').textContent='Puissance ~'+Math.round(power());$('#statsList').innerHTML=bar(p.stats);$('#skillsList').innerHTML=bar(p.skills);$('#hakiList').innerHTML=Object.keys(p.haki).map(function(k){return '<div class="ability-row"><strong>'+e(k)+'</strong><span>'+(p.haki[k]?'Niveau '+Math.round(p.haki[k]):'Non éveillé')+'</span></div>'}).join('');$('#fruitCard').innerHTML=p.fruit?'<strong>'+e(p.fruit)+'</strong>':'Aucun Fruit consommé.';$('#combatStyleCard').innerHTML='<strong>'+e(p.style)+'</strong><p>Combat '+Math.round(p.skills.Combat)+' • Sabre '+Math.round(p.skills.Sabre)+'</p>'}
function renderRel(){$('#relationsList').innerHTML=game.relations.length?game.relations.map(function(r){return '<div class="relation-card"><div class="relation-avatar">'+e(r.name[0])+'</div><div class="relation-copy"><strong>'+e(r.name)+'</strong><span>'+e(r.role)+' • confiance '+Math.round(r.trust)+'%</span></div></div>'}).join(''):'<p class="helper-text">Aucune relation importante.</p>'}
function renderWorld(){var p=game.player,w=game.world,q=inf(),rp=w.pressures[p.region];$('#worldHeadline').textContent='Grande Ère de la Piraterie';$('#worldSubhead').textContent='Année '+w.year+', mois '+(Math.floor(w.month)+1)+'.';$('#worldMeta').innerHTML='<span>Divergence '+Math.round(w.divergence)+'%</span><span>'+p.visited.length+' lieux visités</span>';$('#placeName').textContent=p.travel?'En mer → '+p.travel.destination:p.island;$('#placeDanger').textContent='Danger '+q.danger;$('#placeDescription').textContent=p.travel?'Temps restant : '+Math.max(0,p.travel.remaining).toFixed(1)+' mois.':'Région : '+p.region;$('#placeTags').innerHTML='<span class="chip">'+e(p.region)+'</span>';$('#travelStatus').textContent=p.travel?'Traversée':p.region;$('#travelOptions').innerHTML=p.travel?'<div class="career-card"><p>Utilise AVANCER pour poursuivre.</p></div>':q.routes.map(function(d){var z=req(d);return '<button class="action-card '+(z[0]?'':'locked')+'" data-d="'+e(d)+'"><strong>'+e(d)+'</strong><small>'+e(inf(d).region)+' • danger '+inf(d).danger+(z[0]?'':' • '+z[1])+'</small></button>'}).join('');$$('[data-d]').forEach(function(b){b.onclick=function(){go(b.dataset.d)}});$('#regionMap').innerHTML=REG.map(function(r){var v=p.visited.filter(function(x){return inf(x).region===r}).length,t=Object.keys(PL).filter(function(x){return inf(x).region===r}).length;return '<div class="region-card '+(r===p.region?'active':'')+'"><strong>'+e(r)+'</strong><span>'+v+'/'+t+' lieux</span></div>'}).join('');var ac=CH.filter(function(c){return c[2]===p.region});$('#localActors').innerHTML=ac.length?ac.map(function(c){return '<div class="actor-row"><strong>'+e(c[0])+'</strong><span>'+e(c[1])+' • importance '+c[3]+'</span></div>'}).join(''):'<p class="helper-text">Aucun acteur majeur identifié.</p>';$('#factionOverview').innerHTML=Object.keys(w.factions).map(function(n){return '<div class="faction-card"><strong>'+e(n)+'</strong><span>Puissance '+Math.round(w.factions[n])+'</span></div>'}).join('');$('#regionTitle').textContent=p.region;$('#pressureBars').innerHTML=bar(rp);$('#worldNews').innerHTML=game.news.map(function(n){return '<div class="news-item"><strong>'+e(n.title)+'</strong><span>'+e(n.desc)+'</span></div>'}).join('');$('#divergenceBadge').textContent='Divergence '+Math.round(w.divergence)+'%';$('#canonList').innerHTML=w.canon.map(function(c){return '<div class="canon-item"><span class="status">'+e(c[2])+'</span><strong>'+e(c[0])+'</strong><span>Année '+c[1]+' • résistance '+c[3]+'</span></div>'}).join('');var co=[].concat(game.codex.people,game.codex.places,game.codex.factions,game.codex.fruits).filter(function(v,i,a){return a.indexOf(v)===i});$('#codexList').innerHTML=co.map(function(x){return '<span class="chip">'+e(x)+'</span>'}).join('')}
function render(){if(!game)return;showGame();var p=game.player;$('#ageLabel').textContent=age();$('#locationLabel').textContent=p.travel?'→ '+p.travel.destination:p.island;$('#moneyLabel').textContent=Math.floor(p.money).toLocaleString('fr-FR')+' B';$('#playerName').textContent=p.name;$('#avatarInitial').textContent=p.name.charAt(0).toUpperCase();$('#playerSubtitle').textContent=p.race+' • '+p.region+' • '+p.faction;$('#lifeStatus').textContent=p.situation;$('#repPill').textContent=rep();$('#situationTitle').textContent=p.situation;$('#activityValue').textContent=p.activity;$('#factionValue').textContent=p.faction;$('#healthValue').textContent=Math.round(p.health)+'%';$('#energyValue').textContent=Math.round(p.energy)+'%';var d=$('#dangerBadge');d.textContent=p.danger;d.className='danger-badge '+(p.danger==='Élevé'?'high':p.danger==='Moyen'?'medium':'low');$('#conditionChips').innerHTML=p.conditions.length?p.conditions.map(function(c){return '<span class="chip">'+e(c.name)+'</span>'}).join(''):'<span class="chip">Aucune blessure</span>';$('#advanceBtn').disabled=!game.alive||!!game.pending;$('#advanceHint').textContent=game.pending?'Une décision t’attend':game.mission?'Mission : '+game.mission.title:p.travel?'Navigation en cours':'Le moteur choisit la durée adaptée';if(game.pending){$('#attentionCard').classList.remove('hidden');$('#attentionTitle').textContent=game.pending.title;$('#attentionText').textContent=game.pending.text}else $('#attentionCard').classList.add('hidden');renderTimeline();renderChar();renderAb();renderRel();renderWorld();$('#devOutput').textContent=JSON.stringify({seed:game.seed,power:power(),player:p,world:game.world},null,2)}
function deathModal(){var p=game.player;$('#deathTitle').textContent=p.name+', '+age();$('#deathSummary').innerHTML='<div><span>Cause</span><strong>'+e(game.death.cause)+'</strong></div><div><span>Carrière</span><strong>'+e(p.career)+'</strong></div><div><span>Victoires</span><strong>'+p.wins+'</strong></div><div><span>Lieux</span><strong>'+p.visited.length+'</strong></div>';$('#deathModal').classList.remove('hidden')}
function toast(m){var t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(t._t);t._t=setTimeout(function(){t.classList.add('hidden')},1600)}
function backup(m){backupMode=m;$('#backupModal').classList.remove('hidden');$('#backupTitle').textContent=m==='export'?'Exporter':'Importer';$('#backupText').value=m==='export'?btoa(unescape(encodeURIComponent(JSON.stringify(game)))):'';$('#backupPrimaryBtn').textContent=m==='export'?'Copier':'Importer'}
function bind(){
 $$('.mode-card').forEach(function(b){b.onclick=function(){mode=b.dataset.mode;$$('.mode-card').forEach(function(x){x.classList.toggle('selected',x===b)});$('#customFields').classList.toggle('hidden',mode!=='custom')}});
 $('#newLifeBtn').onclick=function(){make();$('#creationCard').classList.add('hidden');render()};$('#cancelCreate').onclick=function(){$('#creationCard').classList.add('hidden')};$('#advanceBtn').onclick=advance;$('#attentionBtn').onclick=showDecision;$('#homeBtn').onclick=showStart;
 $('#deathHomeBtn').onclick=function(){$('#deathModal').classList.add('hidden');showStart()};$('#deathNewBtn').onclick=function(){localStorage.removeItem(key());$('#deathModal').classList.add('hidden');showStart();$('#creationCard').classList.remove('hidden')};
 $('#timelineFilter').onclick=function(){majorOnly=!majorOnly;renderTimeline()};$$('.nav-item').forEach(function(b){b.onclick=function(){$$('.nav-item').forEach(function(x){x.classList.toggle('active',x===b)});$$('.tab-panel').forEach(function(x){x.classList.toggle('active',x.dataset.panel===b.dataset.tab)});scrollTo(0,0)}});
 $('#devToggle').onclick=function(){if(game)$('#developerPanel').classList.remove('hidden')};$('#closeDev').onclick=function(){$('#developerPanel').classList.add('hidden')};$('#exportSaveBtn').onclick=function(){backup('export')};$('#importSaveBtn').onclick=function(){backup('import')};$('#backupCloseBtn').onclick=function(){$('#backupModal').classList.add('hidden')};
 $('#backupPrimaryBtn').onclick=function(){if(backupMode==='export'){if(navigator.clipboard)navigator.clipboard.writeText($('#backupText').value);toast('Sauvegarde copiée ou prête à copier.')}else try{game=JSON.parse(decodeURIComponent(escape(atob($('#backupText').value.trim()))));save();$('#backupModal').classList.add('hidden');render()}catch(x){toast('Sauvegarde invalide.')}};
 document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')save()});window.addEventListener('pagehide',save)
}
function init(){bind();if(location.protocol!=='file:')$('#localFileWarning').classList.add('hidden');if(/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.matchMedia('(display-mode: standalone)').matches&&location.protocol==='https:')$('#iosInstallCard').classList.remove('hidden');slots();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(function(){})}
init();
})();