(function(){
'use strict';
var $=function(s){return document.querySelector(s)},$$=function(s){return Array.prototype.slice.call(document.querySelectorAll(s))};
var game=null,slot=1,mode='destiny',majorOnly=false,backupMode='export',P='opl-v05-';
var ORIG=['East Blue','North Blue','West Blue','South Blue'],REG=ORIG.concat(['Grand Line','New World']);
var ST=['Force','Vitesse','Agilité','Endurance','Résistance','Réflexes','Discipline','Volonté'];
var SK=['Combat','Sabre','Tir','Navigation','Médecine','Commandement','Discrétion','Science'];
var PL={
'Loguetown':['East Blue',14,['Shells Town','Baratie','Reverse Mountain']],
'Shells Town':['East Blue',8,['Loguetown','Orange Town']],
'Orange Town':['East Blue',9,['Shells Town','Syrup Village']],
'Goa':['East Blue',10,['Shimotsuki','Syrup Village']],
'Shimotsuki':['East Blue',6,['Goa','Baratie']],
'Syrup Village':['East Blue',5,['Orange Town','Goa','Baratie']],
'Baratie':['East Blue',12,['Loguetown','Shimotsuki','Syrup Village']],
'Lvneel':['North Blue',12,['Flevance','Minion Island']],
'Flevance':['North Blue',20,['Lvneel','Minion Island']],
'Minion Island':['North Blue',22,['Flevance','Reverse Mountain']],
'Ohara':['West Blue',8,['Ilusia']],
'Ilusia':['West Blue',14,['Ohara','Reverse Mountain']],
'Baterilla':['South Blue',10,['Torino','Reverse Mountain']],
'Torino':['South Blue',16,['Baterilla']],
'Reverse Mountain':['Grand Line',32,['Loguetown','Minion Island','Ilusia','Baterilla','Twin Cape']],
'Twin Cape':['Grand Line',28,['Reverse Mountain','Whisky Peak']],
'Whisky Peak':['Grand Line',34,['Twin Cape','Little Garden']],
'Little Garden':['Grand Line',39,['Whisky Peak','Drum']],
'Drum':['Grand Line',32,['Little Garden','Alabasta']],
'Alabasta':['Grand Line',37,['Drum','Jaya']],
'Jaya':['Grand Line',43,['Alabasta','Water 7']],
'Water 7':['Grand Line',29,['Jaya','Thriller Bark']],
'Thriller Bark':['Grand Line',48,['Water 7','Sabaody']],
'Sabaody':['Grand Line',45,['Thriller Bark','Fish-Man Island']],
'Fish-Man Island':['Grand Line',44,['Sabaody','Punk Hazard']],
'Punk Hazard':['New World',66,['Fish-Man Island','Dressrosa']],
'Dressrosa':['New World',61,['Punk Hazard','Zou','Whole Cake Island']],
'Zou':['New World',52,['Dressrosa','Wano']],
'Whole Cake Island':['New World',78,['Dressrosa','Wano']],
'Wano':['New World',82,['Zou','Whole Cake Island','Egghead']],
'Egghead':['New World',68,['Wano']]};
var CH=[['Garp','Marine','East Blue',90],['Shanks','Pirates','East Blue',95],['Rayleigh','Pirates','Grand Line',92],['Mihawk','Indépendant','Grand Line',90],['Dragon','Révolutionnaires','Grand Line',98],['Kaido','Pirates','New World',99],['Big Mom','Pirates','New World',99],['Barbe Blanche','Pirates','New World',100]];
var MS={Civil:[['Livraison côtière',18,6500],['Escorte commerciale',28,12000]],Marine:[['Patrouille portuaire',20,9000],['Contrebandiers',38,18000]],Pirates:[['Piller un convoi',42,22000],['Équipage rival',55,33000]],'Chasseur de primes':[['Traquer un hors-la-loi',35,18000],['Capturer un capitaine',52,30000]],Révolutionnaires:[['Acheminer des renseignements',30,0],['Saboter une installation',58,0]],Gouvernement:[['Surveillance discrète',25,10000],['Opération Cipher Pol',64,42000]]};

var TECH={
'Équilibré':[{id:'garde',name:'Garde adaptative',req:12,skill:'Combat',bonus:3},{id:'contre',name:'Contre opportuniste',req:30,skill:'Combat',bonus:5},{id:'enchaînement',name:'Enchaînement complet',req:55,skill:'Combat',bonus:8}],
'Corps-à-corps':[{id:'impact',name:'Impact direct',req:12,skill:'Combat',bonus:4},{id:'rafale',name:'Rafale rapprochée',req:32,skill:'Combat',bonus:6},{id:'briseur',name:'Briseur de garde',req:58,skill:'Combat',bonus:9}],
'Sabreur':[{id:'coupe',name:'Coupe précise',req:12,skill:'Sabre',bonus:4},{id:'iai',name:'Iai rapide',req:34,skill:'Sabre',bonus:7},{id:'lame-distance',name:'Lame à distance',req:62,skill:'Sabre',bonus:10}],
'Tireur':[{id:'tir-vise',name:'Tir visé',req:12,skill:'Tir',bonus:4},{id:'tir-mobile',name:'Tir en mouvement',req:34,skill:'Tir',bonus:7},{id:'tir-longue',name:'Tir longue portée',req:62,skill:'Tir',bonus:10}],
'Mobile / esquive':[{id:'pas-lateral',name:'Pas latéral',req:12,skill:'Combat',bonus:4},{id:'feinte',name:'Feinte éclair',req:34,skill:'Combat',bonus:7},{id:'angle-mort',name:'Angle mort',req:62,skill:'Combat',bonus:10}]
};
var MATCH={'Corps-à-corps':{'Tireur':6},'Tireur':{'Sabreur':5},'Sabreur':{'Équilibré':4},'Mobile / esquive':{'Sabreur':5},'Équilibré':{'Mobile / esquive':3}};
var HAKI_APPS={
Observation:[[1,'Présence'],[25,'Perception étendue'],[55,'Anticipation'],[80,'Vision du futur naissante']],
Armement:[[1,'Renforcement'],[25,'Revêtement'],[55,'Projection'],[80,'Destruction interne']],
Conquérant:[[1,'Intimidation'],[35,'Décharge ciblée'],[70,'Infusion du Conquérant']]
};
function e(s){return String(s==null?'':s).replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]})}
function cl(n,a,b){return Math.max(a,Math.min(b,n))}
function H(s){var x=2166136261>>>0;String(s).split('').forEach(function(c){x=Math.imul(x^c.charCodeAt(0),16777619)});return x>>>0}
function R(k){k=k||'m';var c=game?(game.rng[k]||0):0,s=(game?game.seed:1)^H(k+':'+c);if(game)game.rng[k]=c+1;var t=s+0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}
function pk(a,k){return a[Math.floor(R(k)*a.length)]}
function inf(n){var p=PL[n||game.player.island]||[game.player.region,10,[]];return{region:p[0],danger:p[1],routes:p[2]}}
function age(){var m=game.player.ageMonths,y=Math.floor(m/12),o=Math.floor(m%12);return y?(y+' an'+(y>1?'s':'')+(o?' et '+o+' mois':'')):(o+' mois')}
function key(){return P+slot}
function save(){if(game)localStorage.setItem(key(),JSON.stringify(game))}
function migrate(g){
 if(!g)return null;var p=g.player||{},w=g.world||{};
 g.version=6;g.lastCombat=g.lastCombat||null;g.rng=g.rng||{};
 p.techniques=p.techniques||[];p.techniqueMastery=p.techniqueMastery||{};p.fruitMastery=p.fruitMastery||0;p.fruitAwakened=!!p.fruitAwakened;p.heldFruit=p.heldFruit||null;p.combatXP=p.combatXP||0;p.hakiApplications=p.hakiApplications||{Observation:[],Armement:[],Conquérant:[]};
 p.haki=p.haki||{Observation:0,Armement:0,Conquérant:0};p.latent=p.latent||{Observation:40,Armement:40,Conquérant:0};p.conditions=p.conditions||[];
 w.fruits=w.fruits||['Mera Mera no Mi','Ope Ope no Mi','Hie Hie no Mi','Moku Moku no Mi'];w.fruitRegistry=w.fruitRegistry||{};
 w.fruits.forEach(function(n){if(!w.fruitRegistry[n])w.fruitRegistry[n]={status:p.fruit===n?'consumed':'available',holder:p.fruit===n?p.name:null}});
 g.player=p;g.world=w;return g
}
function load(i){try{return migrate(JSON.parse(localStorage.getItem(P+i)||'null'))}catch(x){return null}}
function tl(t,d,y){game.timeline.unshift({age:age(),title:t,desc:d,type:y||''});game.timeline=game.timeline.slice(0,100)}
function news(t,d){game.news.unshift({title:t,desc:d});game.news=game.news.slice(0,25)}
function press(){var o={};REG.forEach(function(r){o[r]={Piraterie:20+R('w')*25,Marine:30+R('w')*35,Criminalité:15+R('w')*30,Révolution:5+R('w')*20,Prospérité:40+R('w')*35,Instabilité:10+R('w')*25}});return o}
function make(){
 var seed=Number($('#seedInput').value)||Math.floor(Math.random()*2147483647),origin=mode==='custom'?$('#originInput').value:pk(ORIG,'b');
 game={version:6,seed:seed,rng:{},alive:true,pending:null,mission:null,timeline:[],news:[],relations:[],codex:{people:[],places:[],factions:['Civil'],fruits:[]},world:{year:0,month:0,divergence:0,pressures:{},factions:{Marine:82,Pirates:79,Révolutionnaires:56,Gouvernement:94},canon:[['Exécution de Gol D. Roger',0,'completed',100],['Nouvelle génération',18,'future',75],['Guerre au sommet',22,'future',95]],fruits:['Mera Mera no Mi','Ope Ope no Mi','Hie Hie no Mi','Moku Moku no Mi']},player:{name:$('#nameInput').value.trim()||'Kael Maren',difficulty:$('#difficultyInput').value,ageMonths:0,race:mode==='custom'?$('#raceInput').value:pk(['Humain','Humain','Humain','Mink','Homme-poisson'],'b'),origin:origin,region:origin,island:'',situation:'Enfance',activity:'Grandir',faction:'Civil',career:'Aucune',rank:'Enfant',money:3000,health:100,energy:100,danger:'Faible',conditions:[],bounty:0,highestBounty:0,reputation:0,ambition:'Survivre',wins:0,losses:0,travel:null,visited:[],style:mode==='custom'?$('#styleInput').value:pk(['Équilibré','Corps-à-corps','Sabreur','Tireur','Mobile / esquive'],'b'),fruit:null,heldFruit:null,fruitMastery:0,fruitAwakened:false,techniques:[],techniqueMastery:{},combatXP:0,hakiApplications:{Observation:[],Armement:[],Conquérant:[]},haki:{Observation:0,Armement:0,Conquérant:0},latent:{Observation:20+R('h')*60,Armement:20+R('h')*60,Conquérant:R('h')<.04?90:0},stats:{},skills:{},caps:{}}};
 game=migrate(game);var homes=Object.keys(PL).filter(function(n){return PL[n][0]===origin});game.player.island=pk(homes,'b');game.player.visited=[game.player.island];game.codex.places=[game.player.island];game.world.pressures=press();
 ST.forEach(function(k){game.player.stats[k]=8+R('b')*12;game.player.caps[k]=68+R('c')*25});SK.forEach(function(k){game.player.skills[k]=2+R('b')*8;game.player.caps[k]=68+R('c')*25});
 syncPowers();tl('Naissance','Tu nais à '+game.player.island+', dans '+origin+'.','major');news('Grande Ère de la Piraterie','Le monde entre dans une période de bouleversements.');save();return game}
function diff(){return game.player.difficulty==='Casual'?[1.2,.75]:game.player.difficulty==='Ironman'?[.9,1.55]:[1,1]}
function techniqueBonus(){var p=game.player,b=0;(p.techniques||[]).forEach(function(id){var all=[].concat.apply([],Object.keys(TECH).map(function(k){return TECH[k]})),t=all.find(function(x){return x.id===id});if(t)b+=t.bonus});return b}
function power(){var p=game.player,a=ST.reduce(function(s,k){return s+p.stats[k]},0)/ST.length,b=SK.reduce(function(s,k){return s+p.skills[k]},0)/SK.length,h=p.haki.Observation*.18+p.haki.Armement*.22+p.haki.Conquérant*.27,f=p.fruit?(8+p.fruitMastery*.18+(p.fruitAwakened?12:0)):0;return a*.42+b*.38+h+f+techniqueBonus()*.45}
function powerRank(){var v=power();return v<20?'Novice':v<35?'Combattant':v<50?'Confirmé':v<65?'Élite':v<80?'Monstrueux':'Sommet'}
function syncPowers(){var p=game.player,prof=TECH[p.style]||TECH['Équilibré'];prof.forEach(function(t){if((p.skills[t.skill]||0)>=t.req&&p.techniques.indexOf(t.id)<0){p.techniques.push(t.id);p.techniqueMastery[t.id]=1;tl('Nouvelle technique',t.name+' entre dans ton répertoire.','major')}});Object.keys(HAKI_APPS).forEach(function(k){p.hakiApplications[k]=HAKI_APPS[k].filter(function(a){return p.haki[k]>=a[0]}).map(function(a){return a[1]})});if(false){}}
function trainHaki(k,m){var p=game.player;if(!p.haki[k]){if(p.latent[k]>55&&R('h')<.025*m*(p.latent[k]/70)){p.haki[k]=1;tl('Éveil du Haki','Ton Haki de '+k+' s’éveille.','major')}return}p.haki[k]=cl(p.haki[k]+m*(.35+p.latent[k]/160)*cl(1-p.haki[k]/125,.12,1),0,100)}
function trainFruit(m){var p=game.player;if(!p.fruit)return;p.fruitMastery=cl(p.fruitMastery+m*(.55+R('fruit')*.45)*cl(1-p.fruitMastery/120,.15,1),0,100);if(p.fruitMastery>=85&&!p.fruitAwakened&&R('fruit')<.015*m){p.fruitAwakened=true;tl('ÉVEIL DU FRUIT','Ta maîtrise franchit un seuil extraordinaire.','major')}}
function learnMastery(m){var p=game.player;(p.techniques||[]).forEach(function(id){p.techniqueMastery[id]=cl((p.techniqueMastery[id]||1)+m*(.4+R('p')*.5),0,100)});syncPowers()}
function gain(k,n){var p=game.player,b=p.stats[k]!=null?p.stats:p.skills,z=b[k],cap=p.caps[k]||90;if(z>=cap)return 0;var g=n*diff()[0]*cl(1-Math.pow(z/110,1.7),.12,1);b[k]=cl(z+g,0,cap);return g}
function train(m){var p=game.player;if(p.activity==='Haki Observation'){trainHaki('Observation',m);learnMastery(m);return}if(p.activity==='Haki Armement'){trainHaki('Armement',m);learnMastery(m);return}if(p.activity==='Haki Conquérant'){trainHaki('Conquérant',m);learnMastery(m);return}if(p.activity==='Maîtrise du Fruit'){trainFruit(m);learnMastery(m);return}var map={Grandir:['Endurance','Réflexes'],Études:['Discipline','Science'],Entraînement:['Force','Combat'],Navigation:['Navigation','Endurance'],Sabre:['Sabre','Réflexes'],'Formation Marine':['Discipline','Combat'],'Formation Pirates':['Combat','Navigation'],'Formation Révolutionnaires':['Discrétion','Commandement'],'Formation Gouvernement':['Discipline','Discrétion'],Médecine:['Médecine','Discipline'],Explorer:['Réflexes','Navigation']},ks=map[p.activity]||[pk(ST,'p'),pk(SK,'p')];ks.forEach(function(k){gain(k,m*(.5+R('p')*.8))});if(p.fruit&&R('fruit')<.5)trainFruit(m*.35);if(p.haki.Observation&&R('h')<.35)trainHaki('Observation',m*.25);if(p.haki.Armement&&R('h')<.35)trainHaki('Armement',m*.25);learnMastery(m)}
function decision(t,txt,ch){game.pending={title:t,text:txt,choices:ch};save();render();showDecision()}
function showDecision(){if(!game.pending)return;$('#decisionTitle').textContent=game.pending.title;$('#decisionText').textContent=game.pending.text;$('#decisionChoices').innerHTML=game.pending.choices.map(function(c,i){return '<button class="choice-btn" data-c="'+i+'"><strong>'+e(c[0])+'</strong><small>'+e(c[1])+'</small></button>'}).join('');$$('[data-c]').forEach(function(b){b.onclick=function(){var c=game.pending.choices[+b.dataset.c];c[2]();game.pending=null;$('#decisionModal').classList.add('hidden');save();render()}});$('#decisionModal').classList.remove('hidden')}
function join(f,r){var p=game.player;p.faction=f;p.career=f;p.rank=r;p.situation='Carrière';p.activity=f==='Civil'?'Études':'Formation '+f;if(game.codex.factions.indexOf(f)<0)game.codex.factions.push(f);tl('Nouvelle carrière','Tu rejoins '+f+'.','major')}
function career(){decision('Choisir une voie','Ta vie adulte commence.',[['Marine','Missions et promotions.',function(){join('Marine','Recrue')}],['Pirate','Liberté et prime.',function(){join('Pirates','Novice')}],['Chasseur de primes','Contrats indépendants.',function(){join('Chasseur de primes','Indépendant')}],['Civil','Commerce, médecine, science.',function(){join('Civil','Apprenti')}],['Révolutionnaires','Voie clandestine.',function(){join('Révolutionnaires','Sympathisant')}],['Gouvernement','Renseignement et Cipher Pol.',function(){join('Gouvernement','Agent junior')}]])}
function styleEdge(a,b){return(MATCH[a]&&MATCH[a][b])||-((MATCH[b]&&MATCH[b][a])||0)}
function injuryName(sev){if(sev>=3)return pk(['Fracture','Traumatisme','Plaie profonde'],'inj');if(sev===2)return pk(['Entorse','Coupure sérieuse','Contusion profonde'],'inj');return pk(['Ecchymoses','Coupure légère','Douleur musculaire'],'inj')}
function combatProfile(){var p=game.player,weapon=p.style==='Sabreur'?p.skills.Sabre:p.style==='Tireur'?p.skills.Tir:p.skills.Combat,inj=p.conditions.reduce(function(a,c){return a+(c.severity||1)*2},0);return{offense:p.stats.Force*.18+p.stats.Vitesse*.13+p.skills.Combat*.27+weapon*.19+p.haki.Armement*.18+p.haki.Conquérant*.08+(p.fruit?p.fruitMastery*.12:0)+techniqueBonus()*.35,defense:p.stats.Résistance*.2+p.stats.Agilité*.17+p.stats.Réflexes*.18+p.skills.Combat*.16+p.haki.Observation*.22+p.haki.Armement*.08-inj,stamina:p.stats.Endurance*.65+p.energy*.22+p.health*.13}}
function fight(d,t){var p=game.player,styles=['Équilibré','Corps-à-corps','Sabreur','Tireur','Mobile / esquive'],enemyStyle=pk(styles,'f'),terrain=pk(['terrain ouvert','pont de navire','espace étroit','ruelles','terrain accidenté'],'f'),cp=combatProfile(),edge=styleEdge(p.style,enemyStyle),enemyOff=d*(.72+R('f')*.46),enemyDef=d*(.7+R('f')*.44),terrainMod=(terrain==='espace étroit'&&p.style==='Tireur')?-4:(terrain==='terrain ouvert'&&p.style==='Tireur')?4:(terrain==='terrain accidenté'&&p.style==='Mobile / esquive')?4:0,playerScore=cp.offense*.58+cp.defense*.34+cp.stamina*.08+edge+terrainMod+(R('f')-.5)*12,enemyScore=enemyOff*.6+enemyDef*.4+(R('f')-.5)*12,adv=playerScore-enemyScore,chance=cl(.5+adv/100,.03,.97),ok=R('f')<chance,margin=Math.abs(adv)+(R('f')*10),damage=0,outcome='';
 p.energy=cl(p.energy-(5+d*.08),0,100);
 if(ok){p.wins++;p.reputation+=4;p.combatXP+=3+d/18;if(p.faction==='Pirates'){p.bounty+=Math.round(d*1200);p.highestBounty=Math.max(p.highestBounty,p.bounty)}gain('Combat',1+d/42);damage=margin<10?Math.round(2+R('f')*7):Math.round(R('f')*4);p.health=cl(p.health-damage,0,100);outcome=margin>22?'Victoire nette':margin>10?'Victoire':'Victoire difficile';if(p.haki.Armement)trainHaki('Armement',.35);if(p.haki.Observation)trainHaki('Observation',.35);if(p.fruit)trainFruit(.3);tl(t||'Combat',outcome+'. '+(damage?'Tu subis '+damage+'% de dégâts.':'Tu évites les blessures sérieuses.'),'major')}
 else{p.losses++;damage=Math.round(cl(7+(enemyScore-playerScore)*.28+R('f')*18,5,58)*diff()[1]);p.health=cl(p.health-damage,0,100);outcome=damage>35?'Défaite sévère':damage>18?'Défaite':'Repli forcé';if(damage>12){var sev=damage>35?3:damage>22?2:1,inj={name:injuryName(sev),months:sev*(1.5+R('inj')*2),severity:sev};p.conditions.push(inj)}tl(t||'Combat',outcome+'. Tu subis '+damage+'% de dégâts.','danger');if(p.health<=0||R('f')<Math.max(0,(enemyScore-playerScore)/230))die('Mort lors d’un affrontement.')}
 game.lastCombat={title:t||'Combat',outcome:outcome,opponentPower:Math.round((enemyOff+enemyDef)/2),playerPower:Math.round(power()),opponentStyle:enemyStyle,playerStyle:p.style,terrain:terrain,matchup:edge+terrainMod,chance:Math.round(chance*100),damage:damage,log:(edge+terrainMod>2?'Ton style exploite le matchup. ':edge+terrainMod<-2?'Le matchup te désavantage. ':'Le matchup est relativement neutre. ')+(p.haki.Observation?'Ton Observation aide à lire les attaques. ':'')+(p.haki.Armement?' Ton Armement renforce les échanges.':'')};syncPowers();return ok}
function challengeFight(){var p=game.player;if(p.ageMonths<144)return toast('Tu es encore trop jeune pour chercher un vrai défi.');if(p.health<45)return toast('Ta santé est trop basse.');var d=inf().danger+12+R('f')*24;fight(d,'Défi local à '+p.island);save();render();if(!game.alive)deathModal()}
function board(){var a=MS[game.player.faction]||MS.Civil;return a.map(function(m,i){return{id:i,title:m[0],danger:Math.round(m[1]+inf().danger*.28),reward:m[2],months:1+Math.ceil(m[1]/25)}})}
function startMission(i){if(game.mission||game.player.ageMonths<168)return toast('Mission indisponible.');var m=board()[i];game.mission={title:m.title,danger:m.danger,reward:m.reward,remaining:m.months};game.player.situation='Mission';tl('Mission acceptée',m.title+'.','major');save();render()}
function resolveMission(){var m=game.mission,p=game.player,ok=fight(m.danger,'Mission : '+m.title);if(!game.alive)return;if(ok){p.money+=m.reward;p.reputation+=6;tl('Mission accomplie',m.title+' est terminée avec succès.','major')}else tl('Mission échouée',m.title+' échoue.','danger');game.mission=null;p.situation='Carrière'}
function req(d){var r=inf(d).region,p=game.player;if(r==='Grand Line'&&p.skills.Navigation<18)return[false,'Navigation 18'];if(r==='New World'&&(p.skills.Navigation<35||power()<35))return[false,'Navigation 35 + puissance 35'];return[true,'']}
function go(d){var q=req(d);if(!q[0])return toast('Accès verrouillé : '+q[1]);var z=inf(d).danger,mo=Math.max(.5,Math.round((.6+z/35+R('t')*.8)*10)/10);decision('Prendre la mer','Voyager vers '+d+' prendra environ '+mo+' mois.',[['Partir','Danger '+z+'/100',function(){var p=game.player;p.travel={from:p.island,destination:d,remaining:mo,danger:z};p.situation='Navigation';p.activity='Navigation';tl('Départ en mer','Cap sur '+d+'.','major')}],['Rester','Annuler.',function(){}]])}
function travel(m){var p=game.player,t=p.travel;t.remaining-=m;if(R('t')<.18)fight(t.danger*.75,'Incident en mer');if(!game.alive)return;if(t.remaining<=0){p.island=t.destination;p.region=inf(t.destination).region;p.travel=null;p.situation='Arrivée';p.activity='Explorer';if(p.visited.indexOf(p.island)<0)p.visited.push(p.island);if(game.codex.places.indexOf(p.island)<0)game.codex.places.push(p.island);tl('Nouvelle destination','Tu arrives à '+p.island+'.','major')}}
function world(m){var w=game.world,p=game.player;w.month+=m;while(w.month>=12){w.month-=12;w.year++;if(R('w')<.5)news('Mouvements de factions',pk(['La Marine redéploie des bâtiments.','Un nouvel équipage gagne en réputation.','Des agents révolutionnaires sont signalés.'],'w'))}var rp=w.pressures[p.region];Object.keys(rp).forEach(function(k){rp[k]=cl(rp[k]+(R('w')-.5)*m*2,0,100)});w.canon.forEach(function(c){if(c[2]==='future'&&w.year>=c[1]){c[2]=w.divergence>70&&R('w')<.4?'modified':'completed';tl(c[0],c[2]==='modified'?'Le monde diverge fortement.':'Un événement historique a lieu.','canon')}})}
function event(m){if(R('e')>.18+m*.02)return;var p=game.player,x=pk(['relation','money','danger','meet','haki','fruit'],'e');if(x==='relation'){var n=pk(['Mira','Doran','Seline','Rook','Nessa','Toma'],'r'),r={name:n,role:pk(['ami','rival','mentor','collègue'],'r'),affection:30+R('r')*50,respect:25+R('r')*55,trust:20+R('r')*55};game.relations.push(r);tl('Nouvelle rencontre',n+' devient '+r.role+'.','major')}else if(x==='money'){var z=1000+Math.floor(R('e')*12000);p.money+=z;tl('Bonne affaire','Tu gagnes '+z.toLocaleString('fr-FR')+' B.')}else if(x==='danger')fight(inf().danger+10+R('e')*35,'Confrontation imprévue');else if(x==='meet'){var a=CH.filter(function(c){return c[2]===p.region});if(a.length){var c=pk(a,'e');if(game.codex.people.indexOf(c[0])<0)game.codex.people.push(c[0]);tl('Rencontre canonique','Tu croises '+c[0]+' ('+c[1]+').','canon')}}else if(x==='haki'){var k=pk(['Observation','Armement','Conquérant'],'h');if(p.latent[k]>55&&p.haki[k]===0){p.haki[k]=1;syncPowers();tl('Éveil du Haki','Ton Haki de '+k+' s’éveille.','major')}else if(p.haki[k]){trainHaki(k,.6);syncPowers();tl('Instinct affûté','Ton Haki de '+k+' progresse légèrement.')}}else if(x==='fruit'&&!p.fruit&&!p.heldFruit&&R('e')<.32){var av=game.world.fruits.filter(function(n){return !game.world.fruitRegistry[n]||game.world.fruitRegistry[n].status==='available'});if(av.length){var fr=pk(av,'e');decision('Un Fruit du démon','Tu découvres '+fr+'. Rien ne t’oblige à le consommer.',[['Le manger','Obtenir son pouvoir, mais perdre la capacité de nager.',function(){p.fruit=fr;p.fruitMastery=1;game.world.fruitRegistry[fr]={status:'consumed',holder:p.name};if(game.codex.fruits.indexOf(fr)<0)game.codex.fruits.push(fr);tl('Fruit du démon','Tu consommes le '+fr+'.','major')}],['Le conserver','Le garder pour plus tard.',function(){p.heldFruit=fr;game.world.fruitRegistry[fr]={status:'held',holder:p.name};tl('Fruit découvert','Tu conserves le '+fr+'.','major')}],['Le vendre','Transformer cette rareté en Berry.',function(){var val=40000+Math.round(R('fruit')*110000);p.money+=val;game.world.fruitRegistry[fr]={status:'sold',holder:null};tl('Vente exceptionnelle','Tu vends le '+fr+' pour '+val.toLocaleString('fr-FR')+' B.','major')}]])}}}
function die(c){game.alive=false;game.death={cause:c};game.player.health=0;tl('Mort',c,'danger')}
function advance(){if(!game||!game.alive||game.pending)return;var p=game.player,m=p.ageMonths<72?6:p.ageMonths<180?3:game.mission?Math.min(1,game.mission.remaining):p.travel?Math.min(1,p.travel.remaining):1+R('time')*2;m=Math.max(.5,Math.round(m*2)/2);p.ageMonths+=m;world(m);p.health=cl(p.health+m*2,0,100);p.energy=cl(p.energy+m*4,0,100);p.conditions.forEach(function(c){c.months-=m});p.conditions=p.conditions.filter(function(c){return c.months>0});if(p.travel)travel(m);else if(game.mission){game.mission.remaining-=m;train(m);if(game.mission.remaining<=0)resolveMission()}else{train(m);event(m)}if(!game.alive){save();render();deathModal();return}if(p.ageMonths>=72&&p.situation==='Enfance'){p.situation='Formation';p.activity='Études';tl('Formation','Tu commences une formation structurée.','major')}if(p.ageMonths>=180&&p.career==='Aucune'&&!game.pending)career();p.danger=p.conditions.length?'Moyen':inf().danger>45?'Élevé':inf().danger>20?'Moyen':'Faible';save();render()}
function rep(){var r=game.player.reputation;return r>75?'Célèbre':r>40?'Reconnu':r>15?'Connu':'Inconnu'}
function slots(){var b=$('#saveSlots');b.innerHTML='';for(var i=1;i<=3;i++){(function(i){var s=load(i),x=document.createElement('button');x.className='save-slot'+(s?'':' empty');x.innerHTML=s?'<strong>'+e(s.player.name)+'</strong><small>'+Math.floor(s.player.ageMonths/12)+' ans • '+e(s.player.faction)+'<br>'+e(s.player.island)+'</small>':'<strong>＋ Nouvelle vie</strong><small>Emplacement '+i+'</small>';x.onclick=function(){slot=i;if(s){game=s;render()}else $('#creationCard').classList.remove('hidden')};b.appendChild(x)})(i)}}
function bar(o){return Object.keys(o).map(function(k){var v=o[k];return '<div class="stat-row"><span>'+e(k)+'</span><div class="stat-bar"><div class="stat-fill" style="width:'+cl(v,0,100)+'%"></div></div><span class="stat-value">'+Math.round(v)+'</span></div>'}).join('')}
function showGame(){$('#startScreen').classList.remove('active');$('#gameScreen').classList.add('active');$('#bottomNav').classList.remove('hidden');$('#homeBtn').classList.remove('hidden')}
function showStart(){game=null;$('#gameScreen').classList.remove('active');$('#startScreen').classList.add('active');$('#bottomNav').classList.add('hidden');$('#homeBtn').classList.add('hidden');slots()}
function renderTimeline(){var a=game.timeline.filter(function(x){return !majorOnly||['major','danger','canon'].indexOf(x.type)>=0});$('#timeline').innerHTML=a.slice(0,45).map(function(x){return '<div class="timeline-item '+e(x.type)+'"><span class="timeline-dot"></span><span class="timeline-age">'+e(x.age)+'</span><div class="timeline-title">'+e(x.title)+'</div><div class="timeline-desc">'+e(x.desc)+'</div></div>'}).join('')}
function renderChar(){var p=game.player;$('#identityGrid').innerHTML=[['Nom',p.name],['Origine',p.origin],['Race',p.race],['Lieu',p.island],['Faction',p.faction],['Réputation',rep()]].map(function(x){return '<div class="info-cell"><span>'+e(x[0])+'</span><strong>'+e(x[1])+'</strong></div>'}).join('');$('#careerCard').innerHTML='<strong>'+e(p.career)+'</strong><p>Rang : '+e(p.rank)+' • Prime : '+Math.floor(p.bounty).toLocaleString('fr-FR')+' B • Victoires : '+p.wins+'</p>';$('#ambitionCard').innerHTML='<strong>'+e(p.ambition)+'</strong><p>Orientation personnelle.</p>';var aa=['Survivre','Devenir puissant','Explorer le monde','Faire fortune','Entrer dans l’histoire'];$('#ambitionOptions').innerHTML=aa.map(function(a){return '<button class="action-card '+(p.ambition===a?'active':'')+'" data-a="'+e(a)+'"><strong>'+e(a)+'</strong></button>'}).join('');$$('[data-a]').forEach(function(b){b.onclick=function(){p.ambition=b.dataset.a;save();renderChar()}});$('#missionBoard').innerHTML=game.mission?'<div class="mission-card active-mission"><strong>'+e(game.mission.title)+'</strong><p>'+game.mission.remaining.toFixed(1)+' mois restants</p></div>':board().map(function(m){return '<button class="mission-card" data-m="'+m.id+'"><strong>'+e(m.title)+'</strong><p>Danger '+m.danger+' • '+m.reward.toLocaleString('fr-FR')+' B</p></button>'}).join('');$$('[data-m]').forEach(function(b){b.onclick=function(){startMission(+b.dataset.m)}});var acts=['Études','Entraînement','Navigation','Sabre','Médecine',p.faction==='Marine'?'Formation Marine':p.faction==='Pirates'?'Formation Pirates':p.faction==='Révolutionnaires'?'Formation Révolutionnaires':p.faction==='Gouvernement'?'Formation Gouvernement':'Explorer'];if(p.haki.Observation)acts.push('Haki Observation');if(p.haki.Armement)acts.push('Haki Armement');if(p.haki.Conquérant)acts.push('Haki Conquérant');if(p.fruit)acts.push('Maîtrise du Fruit');$('#activityOptions').innerHTML=acts.map(function(a){return '<button class="action-card '+(p.activity===a?'active':'')+'" data-act="'+e(a)+'"><strong>'+e(a)+'</strong></button>'}).join('');$$('[data-act]').forEach(function(b){b.onclick=function(){p.activity=b.dataset.act;save();renderChar()}});$('#crewSection').classList.toggle('hidden',p.faction!=='Pirates');if(p.faction==='Pirates'){$('#crewName').textContent='Équipage pirate';$('#crewMorale').textContent='Moral '+Math.round(55+p.reputation/3)+'%';$('#crewDetails').innerHTML='<div class="career-card"><p>Recrutements et pertes émergent pendant la carrière.</p></div>'}$('#equipmentList').innerHTML=['Tenue de voyage',p.style,p.fruit||'Aucun Fruit'].map(function(x){return '<span class="chip">'+e(x)+'</span>'}).join('');$('#storageStatus').textContent='Autosave local'}
function renderAb(){var p=game.player;$('#powerEstimate').textContent='Puissance ~'+Math.round(power())+' • '+powerRank();$('#statsList').innerHTML=bar(p.stats);$('#skillsList').innerHTML=bar(p.skills);$('#hakiList').innerHTML=Object.keys(p.haki).map(function(k){return '<div class="ability-row"><strong>'+e(k)+'</strong><span>'+(p.haki[k]?'Niveau '+Math.round(p.haki[k]):'Non éveillé')+'</span></div>'}).join('');$('#fruitCard').innerHTML=p.fruit?'<strong>'+e(p.fruit)+'</strong><div class="mastery-meter"><div style="width:'+p.fruitMastery+'%"></div></div><span>Maîtrise '+Math.round(p.fruitMastery)+'%</span>':p.heldFruit?'<strong>'+e(p.heldFruit)+'</strong><p>Fruit conservé, non consommé.</p>':'Aucun Fruit consommé.';
 var all=[].concat.apply([],Object.keys(TECH).map(function(k){return TECH[k]})),prof=TECH[p.style]||TECH['Équilibré'];$('#techniqueCount').textContent=(p.techniques||[]).length+' maîtrisées';$('#techniqueList').innerHTML=prof.map(function(t){var ok=p.techniques.indexOf(t.id)>=0,m=p.techniqueMastery[t.id]||0;return '<div class="technique-card '+(ok?'':'locked')+'"><strong>'+e(t.name)+'</strong><span>'+(ok?'Maîtrise '+Math.round(m)+'%':'Requiert '+e(t.skill)+' '+t.req)+'</span><small>Bonus de combat '+t.bonus+'</small></div>'}).join('')+(p.fruit&&p.fruitMastery>=20?'<div class="technique-card"><strong>Application du '+e(p.fruit)+'</strong><span>Maîtrise '+Math.round(p.fruitMastery)+'%</span><small>'+(p.fruitAwakened?'Éveil acquis':'Le pouvoir évolue avec la pratique réelle.')+'</small></div>':'');
 $('#hakiApplications').innerHTML=Object.keys(p.hakiApplications).map(function(k){var a=p.hakiApplications[k];return '<div class="haki-app"><strong>'+e(k)+'</strong><small>'+(a.length?e(a.join(' • ')):'Aucune application connue')+'</small></div>'}).join('');
 $('#fruitMasteryCard').innerHTML=p.fruit?'<strong>'+e(p.fruit)+'</strong><div class="mastery-meter"><div style="width:'+p.fruitMastery+'%"></div></div><p>'+Math.round(p.fruitMastery)+'% de maîtrise'+(p.fruitAwakened?' • ÉVEIL':'')+'.</p>':p.heldFruit?'<strong>'+e(p.heldFruit)+'</strong><p>Tu le conserves sans l’avoir mangé.</p><button id="eatHeldFruit" class="primary-btn small">Le consommer</button>':'<strong>Aucun pouvoir</strong><p>Les Fruits existent physiquement dans le monde et doivent être trouvés.</p>';
 var eat=$('#eatHeldFruit');if(eat)eat.onclick=function(){var fr=p.heldFruit;p.heldFruit=null;p.fruit=fr;p.fruitMastery=1;game.world.fruitRegistry[fr]={status:'consumed',holder:p.name};tl('Fruit du démon','Tu décides finalement de consommer le '+fr+'.','major');save();renderAb()};
 $('#combatStyleCard').innerHTML='<strong>'+e(p.style)+'</strong><p>Combat '+Math.round(p.skills.Combat)+' • Sabre '+Math.round(p.skills.Sabre)+' • Tir '+Math.round(p.skills.Tir)+'</p><span class="power-rank">'+powerRank()+'</span>';$('#combatActions').innerHTML='<button id="challengeBtn" class="action-card"><strong>Défi local</strong><small>Affronter un adversaire cohérent avec la zone actuelle.</small></button><button id="martialTrainBtn" class="action-card"><strong>Priorité combat</strong><small>Passer l’activité principale à Entraînement.</small></button>';$('#challengeBtn').onclick=challengeFight;$('#martialTrainBtn').onclick=function(){p.activity='Entraînement';save();renderChar();toast('Activité : Entraînement')};
 if(game.lastCombat){$('#combatReportSection').classList.remove('hidden');var c=game.lastCombat,o=$('#combatOutcome');o.textContent=c.outcome;o.className='badge '+(c.outcome.indexOf('Victoire')>=0?'outcome-win':'outcome-loss');$('#combatReport').innerHTML='<div><span>Puissance</span><strong>'+c.playerPower+' vs '+c.opponentPower+'</strong></div><div><span>Styles</span><strong>'+e(c.playerStyle)+' vs '+e(c.opponentStyle)+'</strong></div><div><span>Terrain</span><strong>'+e(c.terrain)+'</strong></div><div><span>Chance estimée</span><strong>'+c.chance+'%</strong></div><div class="combat-log">'+e(c.log)+'</div>'}else $('#combatReportSection').classList.add('hidden')}
function renderRel(){$('#relationsList').innerHTML=game.relations.length?game.relations.map(function(r){return '<div class="relation-card"><div class="relation-avatar">'+e(r.name[0])+'</div><div class="relation-copy"><strong>'+e(r.name)+'</strong><span>'+e(r.role)+' • confiance '+Math.round(r.trust)+'%</span></div></div>'}).join(''):'<p class="helper-text">Aucune relation importante.</p>'}
function renderWorld(){var p=game.player,w=game.world,q=inf(),rp=w.pressures[p.region];$('#worldHeadline').textContent='Grande Ère de la Piraterie';$('#worldSubhead').textContent='Année '+w.year+', mois '+(Math.floor(w.month)+1)+'.';$('#worldMeta').innerHTML='<span>Divergence '+Math.round(w.divergence)+'%</span><span>'+p.visited.length+' lieux visités</span>';$('#placeName').textContent=p.travel?'En mer → '+p.travel.destination:p.island;$('#placeDanger').textContent='Danger '+q.danger;$('#placeDescription').textContent=p.travel?'Temps restant : '+Math.max(0,p.travel.remaining).toFixed(1)+' mois.':'Région : '+p.region;$('#placeTags').innerHTML='<span class="chip">'+e(p.region)+'</span>';$('#travelStatus').textContent=p.travel?'Traversée':p.region;$('#travelOptions').innerHTML=p.travel?'<div class="career-card"><p>Utilise AVANCER pour poursuivre.</p></div>':q.routes.map(function(d){var z=req(d);return '<button class="action-card '+(z[0]?'':'locked')+'" data-d="'+e(d)+'"><strong>'+e(d)+'</strong><small>'+e(inf(d).region)+' • danger '+inf(d).danger+(z[0]?'':' • '+z[1])+'</small></button>'}).join('');$$('[data-d]').forEach(function(b){b.onclick=function(){go(b.dataset.d)}});$('#regionMap').innerHTML=REG.map(function(r){var v=p.visited.filter(function(x){return inf(x).region===r}).length,t=Object.keys(PL).filter(function(x){return inf(x).region===r}).length;return '<div class="region-card '+(r===p.region?'active':'')+'"><strong>'+e(r)+'</strong><span>'+v+'/'+t+' lieux</span></div>'}).join('');var ac=CH.filter(function(c){return c[2]===p.region});$('#localActors').innerHTML=ac.length?ac.map(function(c){return '<div class="actor-row"><strong>'+e(c[0])+'</strong><span>'+e(c[1])+' • importance '+c[3]+'</span></div>'}).join(''):'<p class="helper-text">Aucun acteur majeur identifié.</p>';$('#factionOverview').innerHTML=Object.keys(w.factions).map(function(n){return '<div class="faction-card"><strong>'+e(n)+'</strong><span>Puissance '+Math.round(w.factions[n])+'</span></div>'}).join('');$('#regionTitle').textContent=p.region;$('#pressureBars').innerHTML=bar(rp);$('#worldNews').innerHTML=game.news.map(function(n){return '<div class="news-item"><strong>'+e(n.title)+'</strong><span>'+e(n.desc)+'</span></div>'}).join('');$('#divergenceBadge').textContent='Divergence '+Math.round(w.divergence)+'%';$('#canonList').innerHTML=w.canon.map(function(c){return '<div class="canon-item"><span class="status">'+e(c[2])+'</span><strong>'+e(c[0])+'</strong><span>Année '+c[1]+' • résistance '+c[3]+'</span></div>'}).join('');var co=[].concat(game.codex.people,game.codex.places,game.codex.factions,game.codex.fruits).filter(function(v,i,a){return a.indexOf(v)===i});$('#codexList').innerHTML=co.map(function(x){return '<span class="chip">'+e(x)+'</span>'}).join('')}
function render(){if(!game)return;showGame();var p=game.player;$('#ageLabel').textContent=age();$('#locationLabel').textContent=p.travel?'→ '+p.travel.destination:p.island;$('#moneyLabel').textContent=Math.floor(p.money).toLocaleString('fr-FR')+' B';$('#playerName').textContent=p.name;$('#avatarInitial').textContent=p.name.charAt(0).toUpperCase();$('#playerSubtitle').textContent=p.race+' • '+p.region+' • '+p.faction;$('#lifeStatus').textContent=p.situation;$('#repPill').textContent=rep();$('#situationTitle').textContent=p.situation;$('#activityValue').textContent=p.activity;$('#factionValue').textContent=p.faction;$('#healthValue').textContent=Math.round(p.health)+'%';$('#energyValue').textContent=Math.round(p.energy)+'%';var d=$('#dangerBadge');d.textContent=p.danger;d.className='danger-badge '+(p.danger==='Élevé'?'high':p.danger==='Moyen'?'medium':'low');$('#conditionChips').innerHTML=p.conditions.length?p.conditions.map(function(c){return '<span class="chip">'+e(c.name)+'</span>'}).join(''):'<span class="chip">Aucune blessure</span>';$('#advanceBtn').disabled=!game.alive||!!game.pending;$('#advanceHint').textContent=game.pending?'Une décision t’attend':game.mission?'Mission : '+game.mission.title:p.travel?'Navigation en cours':'Le moteur choisit la durée adaptée';if(game.pending){$('#attentionCard').classList.remove('hidden');$('#attentionTitle').textContent=game.pending.title;$('#attentionText').textContent=game.pending.text}else $('#attentionCard').classList.add('hidden');renderTimeline();renderChar();renderAb();renderRel();renderWorld();$('#devOutput').textContent=JSON.stringify({seed:game.seed,power:power(),player:p,world:game.world},null,2)}
function deathModal(){var p=game.player;$('#deathTitle').textContent=p.name+', '+age();$('#deathSummary').innerHTML='<div><span>Cause</span><strong>'+e(game.death.cause)+'</strong></div><div><span>Carrière</span><strong>'+e(p.career)+'</strong></div><div><span>Victoires</span><strong>'+p.wins+'</strong></div><div><span>Lieux</span><strong>'+p.visited.length+'</strong></div>';$('#deathModal').classList.remove('hidden')}
function toast(m){var t=$('#toast');t.textContent=m;t.classList.remove('hidden');clearTimeout(t._t);t._t=setTimeout(function(){t.classList.add('hidden')},1600)}
function backup(m){backupMode=m;$('#backupModal').classList.remove('hidden');$('#backupTitle').textContent=m==='export'?'Exporter':'Importer';$('#backupText').value=m==='export'?btoa(unescape(encodeURIComponent(JSON.stringify(game)))):'';$('#backupPrimaryBtn').textContent=m==='export'?'Copier':'Importer'}
function bind(){
 $$('.mode-card').forEach(function(b){b.onclick=function(){mode=b.dataset.mode;$$('.mode-card').forEach(function(x){x.classList.toggle('selected',x===b)});$('#customFields').classList.toggle('hidden',mode!=='custom')}});
 $('#newLifeBtn').onclick=function(){make();$('#creationCard').classList.add('hidden');render()};$('#cancelCreate').onclick=function(){$('#creationCard').classList.add('hidden')};$('#advanceBtn').onclick=advance;$('#attentionBtn').onclick=showDecision;$('#homeBtn').onclick=showStart;
 $('#deathHomeBtn').onclick=function(){$('#deathModal').classList.add('hidden');showStart()};$('#deathNewBtn').onclick=function(){localStorage.removeItem(key());$('#deathModal').classList.add('hidden');showStart();$('#creationCard').classList.remove('hidden')};
 $('#timelineFilter').onclick=function(){majorOnly=!majorOnly;renderTimeline()};$$('.nav-item').forEach(function(b){b.onclick=function(){$$('.nav-item').forEach(function(x){x.classList.toggle('active',x===b)});$$('.tab-panel').forEach(function(x){x.classList.toggle('active',x.dataset.panel===b.dataset.tab)});scrollTo(0,0)}});
 $('#devToggle').onclick=function(){if(game)$('#developerPanel').classList.remove('hidden')};$('#closeDev').onclick=function(){$('#developerPanel').classList.add('hidden')};$('#exportSaveBtn').onclick=function(){backup('export')};$('#importSaveBtn').onclick=function(){backup('import')};$('#backupCloseBtn').onclick=function(){$('#backupModal').classList.add('hidden')};
 $('#backupPrimaryBtn').onclick=function(){if(backupMode==='export'){if(navigator.clipboard)navigator.clipboard.writeText($('#backupText').value);toast('Sauvegarde copiée ou prête à copier.')}else try{game=migrate(JSON.parse(decodeURIComponent(escape(atob($('#backupText').value.trim())))));save();$('#backupModal').classList.add('hidden');render()}catch(x){toast('Sauvegarde invalide.')}};
 document.addEventListener('visibilitychange',function(){if(document.visibilityState==='hidden')save()});window.addEventListener('pagehide',save)
}
function init(){bind();if(location.protocol!=='file:')$('#localFileWarning').classList.add('hidden');if(/iPad|iPhone|iPod/.test(navigator.userAgent)&&!window.matchMedia('(display-mode: standalone)').matches&&location.protocol==='https:')$('#iosInstallCard').classList.remove('hidden');slots();if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('sw.js').catch(function(){})}
init();
})();