import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('index.html','utf8');
const hub=fs.readFileSync('src/v95/action-hub-runtime-v95.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));
const inline=html.match(/<script>([\s\S]*?)<\/script>/)?.[1];
assert(inline,'Inline game script missing');
new Function(inline);
assert(/const GAME_VERSION\s*=\s*'10\.2\.0'/.test(html),'V10.2 release missing');
assert(/const SAVE_VERSION\s*=\s*1000/.test(html),'Save format incompatibility');
assert(sw.includes('one-piece-life-v10-2-0'),'Offline cache out of date');
assert(manifest.description.includes('V10.2'),'PWA metadata out of date');
const a=inline.indexOf('function v100Status(id)');
const b=inline.indexOf('function v100Act(id)',a);
const c=inline.indexOf('function v100AdvanceYear()',b);
const d=inline.indexOf('function v100RenderManualPanel()',c);
const e=inline.indexOf('function v91Module()',d);
assert(a>0&&a<b&&b<c&&c<d&&d<e,'Manual action functions not properly integrated');
const status=inline.slice(a,b),action=inline.slice(b,c),year=inline.slice(c,d),panel=inline.slice(d,e);
assert(status.includes('mod.status(state,id')&&status.includes('v102Context(id)'),'Manual status not centrally checked');
assert(action.includes('st=v100Status(id)')&&action.includes('mod.perform(state,id'),'Manual execution bypasses unified status and effect commit');
assert(action.includes('p.energy=clamp(p.energy-availability.cost,0,100)'),'Navigation energy debit missing');
assert(action.includes('JSON.stringify(game)')&&action.includes('JSON.parse(backup)'),'Atomic rollback missing');
assert(panel.includes('v100Status(id)')&&panel.includes("st.available?'':'disabled'"),'Manual buttons not controlled by shared status');
assert(!panel.includes("p.career==='Aucune'"),'Panel duplicates business rules');
assert(hub.includes('bridge.manualStatus?.(id)'),'Hub bypasses shared action status');
assert(!hub.includes("if(id==='work'&&(p.career==='Aucune'||p.travel))"),'Hub duplicates career prerequisites');
const execute=hub.slice(hub.indexOf('  function execute(id){'),hub.indexOf('  function star(id){'));
assert(execute.indexOf('const ok=bridge.execute(id)')<execute.indexOf('engine.recordAction(state,id)'),'Failed Hub action recorded');
assert(year.includes('v61EventsSince(before)')&&year.includes('v80CompleteYear(yearEvents,report)'),'Annual director events missing');
for(const forbidden of ['careerTick(','trainProgress(','tickMission(','tickTravel(','v69AnnualEconomy('])assert(!year.includes(forbidden),'Passive career progress through aging: '+forbidden);
console.log('V10.1 COMPATIBILITY QA ON V10.2 OK');
