import fs from 'node:fs';
import vm from 'node:vm';
const assert=(x,m)=>{if(!x)throw Error(m)};
const html=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),css=fs.readFileSync('src/v100/manual-life-v100.css','utf8');
const paths=['src/core/module-registry.js','src/data/manual-life-v100.js','src/v100/manual-life-engine-v100.js'];
const ctx={console,Math,JSON,Object,Array,String,Number,Set,Map};
ctx.window=ctx;vm.createContext(ctx);
for(const path of paths)vm.runInContext(fs.readFileSync(path,'utf8'),ctx,{filename:path});
const mod=ctx.OPL_MODULES.get('manualLifeEngineV100'),data=ctx.OPL_MODULES.get('manualLifeDataV100');
assert(mod&&data,'Manual life engine is unavailable');
assert(mod.version==='10.0.0'&&data.version==='10.0.0','Manual life version mismatch');
const start=mod.normalize({},18);
assert(start.year===18&&start.mode==='manual'&&!Object.values(start.spent).length,'New manual game must start with available actions');
let state=mod.use(start,'work',18,75);
assert(state.changed&&state.state.spent.work===1,'Manual work not consumed');
assert(!mod.status(state.state,'work',18,75).available,'Repeated work should be blocked in the same year');
assert(mod.status(state.state,'training',18,75).remaining===2,'Training quota incorrect');
state=mod.use(state.state,'training',18,75);
state=mod.use(state.state,'training',18,63);
assert(!mod.status(state.state,'training',18,63).available,'Training yearly limit not applied');
assert(!mod.use(state.state,'training',18,60).changed,'Exhausted training should not spend extra action');
assert(!mod.use(state.state,'promotion',18,0).changed,'Insufficient energy should block promotions');
const newYear=mod.nextYear(state.state,19);
assert(newYear.year===19&&Object.keys(newYear.spent).length===0,'New year must replenish all yearly action limits');
assert(mod.status(newYear,'work',19,75).available&&mod.status(newYear,'training',19,75).remaining===2,'Actions must become available again next year');
assert(newYear.total===state.state.total,'Lifetime action count should remain persistent');
const malformed=mod.normalize({year:20,spent:{work:999,training:-45,evil:34},total:-17},20);
assert(malformed.spent.work===1&&malformed.spent.training===0&&malformed.spent.evil===undefined,'Save migration must bound per-action limits');
for(const p of ['src/data/manual-life-v100.js','src/v100/manual-life-engine-v100.js','src/v100/manual-life-v100.css'])assert(html.includes(p)&&sw.includes(p),'V10 asset missing '+p);
assert(html.includes('ONE PIECE LIFE — V10.2'),'V10 title missing');
assert(/const GAME_VERSION\s*=\s*'10\.2\.0';/.test(html),'GAME_VERSION missing');
assert(/const SAVE_VERSION\s*=\s*1000;/.test(html),'SAVE_VERSION missing');
assert(sw.includes('one-piece-life-v10-2-0'),'V10 cache missing');
assert(html.includes('function advance(){return v100AdvanceYear()}'),'Age button must call new manual progression handler');
const startFn=html.indexOf('function v100AdvanceYear()'),endFn=html.indexOf('function v100RenderManualPanel()',startFn);
assert(startFn>=0&&endFn>startFn,'Annual handler missing');
const annual=html.slice(startFn,endFn);
for(const forbidden of ['careerTick(','trainProgress(','v62MonthlyPlanEffects(','tickMission(','tickTravel(','v61ResumeAnnualTurn(','v61StartAnnualTurn(','v69AnnualEconomy(','v78AnnualHousehold('])
 assert(!annual.includes(forbidden),'Annual age triggers passive progression: '+forbidden);
for(const used of ['advanceClock(12)','simulateWorld(12)','v83AnnualWorldTick()','v82AnnualWorldTick()','mod.nextYear','naturalMortality(12)'])
 assert(annual.includes(used),'Missing necessary time-world advance: '+used);
assert(html.includes('function v100Act(id)')&&html.includes("if(id==='work')")&&html.includes("if(id==='promotion')"),'Manual career bridge missing');
assert(html.includes("if(kind==='manual')return v100Act(chunks[1])"),'Action Hub manual dispatcher missing');
assert(css.includes('#v90PresetShell')&&css.includes('#careerAnnualActions'),'Legacy auto-plan controls must be hidden');
const runtime=fs.readFileSync('src/v95/action-hub-runtime-v95.js','utf8');
assert(!runtime.includes('for(const [key,item] of Object.entries(presets))'),'Action Hub cannot offer automated annual plans');
assert(runtime.includes('manual:')&&runtime.includes('bridge.manualStatus'),'Manual actions must appear in Action Hub');
new Function(html.match(/<script>([\s\S]*?)<\/script>/)?.[1]||'');
console.log('V10.0 MANUAL LIFE QA OK',JSON.stringify({actions:Object.keys(data.limits),yearRestored:newYear.year,total:newYear.total}));
