import fs from 'node:fs';

const app=fs.readFileSync('app.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=fs.readFileSync('manifest.webmanifest','utf8');
const pack=fs.readFileSync('content-v1.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');

new Function(app);
new Function(pack);
JSON.parse(manifest);

if(!html.includes('<title>ONE PIECE LIFE — V5.0</title>') || !html.includes('V5.0 • Grand Journey')) throw new Error('index.html does not expose V5.0 consistently');
if(!app.includes('version:28') || !app.includes('g.version=28')) throw new Error('compatible GameState 28 migration is missing');
if(!html.includes('<script src="content-v1.js"></script>')) throw new Error('content pack is not loaded');
if(html.indexOf('content-v1.js')>html.indexOf('app.js')) throw new Error('content pack must load before app.js');
if(!sw.includes('content-v1.js')) throw new Error('PWA cache does not include content-v1.js');

const dynamicIds=new Set(['eatHeldFruit','challengeBtn','martialTrainBtn','changeCareerBtn','careerRecordBtn','upgradeHousingBtn','investBusinessBtn','partnerTimeBtn','marryBtn','breakupBtn','welcomeChildBtn','orgBondBtn','orgRecruitBtn','orgTrainBtn','orgFundBtn','orgSupplyBtn','orgRepairBtn','orgUpgradeBtn','layLowBtn','surrenderBtn','escapeBtn','claimDomainBtn','fortifyDomainBtn','affiliateCrewBtn','launchCampaignBtn','seekMentorBtn','exploreIslandBtn','seekRumorBtn','specializationChoiceBtn','ambitionChoiceBtn','timelineMoreBtn','expandRelationsBtn']);
const ids=[...app.matchAll(/\$\('#([^']+)'\)/g)].map(m=>m[1]);
const missing=[...new Set(ids)].filter(id=>!dynamicIds.has(id)&&!html.includes('id="'+id+'"'));
if(missing.length) throw new Error('Missing HTML ids: '+missing.join(', '));

if(!app.includes('function careerTick') || !app.includes('var CAREERS=')) throw new Error('career engine missing');
if(!app.includes('function worldMonthStep') || !app.includes('function simulateCrews') || !app.includes('function simulateActors') || !app.includes('function simulateConflicts')) throw new Error('living world engine missing');
if(!app.includes('function lifeTick') || !app.includes('function continueWithHeir') || !app.includes('function checkAchievements')) throw new Error('life simulator engine missing');
if(!app.includes('function processCanonEvents') || !app.includes('function resolveCanonEvent') || !app.includes('function simulateCanonBranches') || !app.includes('function markPlayerCanonImpact') || !app.includes('function canonTimelineMode')) throw new Error('V3.5 causal canon engine missing');
if(!app.includes('CANON_EVENTS') || !app.includes('SPECIAL_TECHNIQUES') || !app.includes('pickFruit')) throw new Error('V1 content integration missing');
if(!app.includes('relationshipStatus') || !app.includes('children') || !app.includes('netWorthPeak')) throw new Error('family/economy state missing');
if(!app.includes("Mobilité:{keys:['Vitesse','Agilité']") || !app.includes("Mental:{keys:['Volonté','Discipline']")) throw new Error('V2.1 focused progression profiles missing');
if(!app.includes('var SPEC_PROFILES=') || !app.includes('function careerQualification') || !app.includes('function careerActivityFit')) throw new Error('V2.2 meaningful career engine missing');
if(!app.includes('var SIMPLE_FOCUS=') || !app.includes('function recommendedFocus') || !app.includes('function normalizeActivityFocus')) throw new Error('V2.3 adaptive focus engine missing');
if(!app.includes("label:'Progresser'") || !app.includes("label:'Situation'") || !app.includes("label:'Monde'")) throw new Error('V2.3 simplified navigation missing');
if(!app.includes('function specializationDecision') || !app.includes('function ambitionDecision')) throw new Error('V2.3 simplified choice flows missing');
if(!app.includes("'Auto':{label:'Auto'") || !app.includes("if(p.focus==='Auto')return recommendedFocus()")) throw new Error('V2.4 Auto focus missing');
if(!app.includes("min:5.5,max:7.5") || !app.includes("min:4,max:6")) throw new Error('V5.0 flow pacing missing');
if(!app.includes("prisonCritical?1:2") || !app.includes("prisonCritical?2:4")) throw new Error('V5.0 detention pacing missing');
if(!app.includes("ws.actorHistory.slice(0,90)") || !app.includes("ws.crewHistory.slice(0,70)") || !app.includes("ws.sagaHistory.slice(0,60)") || !app.includes("enumerable:false")) throw new Error('V5.0 living-world save compaction missing');
if(!app.includes('function advanceSlice') || !app.includes('tooManyMoments=loop.momentSeq-startMoments>=4')) throw new Error('V2.4 segmented advance engine missing');
if(!app.includes('timelineExpanded') || !app.includes('Voir toute l’histoire')) throw new Error('V2.4 compact timeline expansion missing');
if(!app.includes("group=sectionState.character||'profile'")) throw new Error('V2.4 lazy character rendering missing');
if(!app.includes('function renderWorldExplore') || !app.includes('function renderWorldState') || !app.includes('function renderWorldHistory')) throw new Error('V2.4 lazy world rendering missing');
if(!app.includes('function renderRelClose') || !app.includes('function renderRelNetwork') || !app.includes('function relationActionDecision')) throw new Error('V2.4 contextual relation UI missing');
if(!app.includes('function renderAbProgress') || !app.includes('function renderAbPowers') || !app.includes('function renderAbDetails')) throw new Error('V2.4 lazy progression rendering missing');
if(!app.includes("activityGrowthKeys(currentFocus())")) throw new Error('V2.4 focus-aware event engine missing');
if(!app.includes('function assignActorIntent') || !app.includes('function resolveActorIntent') || !app.includes('function crewIntentTick')) throw new Error('V2.5 world intention engine missing');
if(!app.includes('function weightedIntent') || !app.includes('function weightedPool')) throw new Error('V2.5 context-aware intent weighting missing');
if(!app.includes('function eventNoveltyWeight') || !app.includes('function missionNoveltyScore') || !app.includes('function storyNoveltyWeight')) throw new Error('V2.5 fun-flow novelty director missing');
if(!app.includes("'mentor-lesson'") || !app.includes("'crew-pressure'") || !app.includes("'family-crossroads'") || !app.includes("'horizon-call'")) throw new Error('V2.5 expanded story variety missing');
if(!app.includes("PALIER DE PUISSANCE")) throw new Error('V2.5 progression milestone feedback missing');
if(!app.includes('function recordSignatureMoment') || !app.includes('function missionImportance') || !app.includes('function missionStakes')) throw new Error('V2.6 signature moment engine missing');
if(!app.includes('function syncRivalryMilestone') || !app.includes("recordSignatureMoment('Accomplissement")) throw new Error('V2.6 rivalry or achievement signature integration missing');
if(!app.includes("eng.history.slice(0,4)") || !app.includes('worldHighlights:worldHighlights') || !app.includes("label:'Ouverture'")) throw new Error('V2.5 fun-flow feedback surfaces missing');
if(!app.includes("Object.keys(bonus||{})") || !app.includes("intent==='Recruter'") || !app.includes("poursuit ses activités dans")) throw new Error('V2.5 autonomy hardening missing');
if(!app.includes('function assignNpcIntent') || !app.includes('function npcSocialTick') || !app.includes('npcLinks')) throw new Error('V2.5 autonomous NPC network missing');
if(!app.includes('function npcCareerPromotionChance') || !app.includes('function tryNpcCareerPromotion')) throw new Error('V2.5 NPC career pacing missing');
if(!app.includes('function worldMissionOpportunities') || !app.includes('function applyWorldMissionOutcome')) throw new Error('V2.5 causal mission engine missing');
if(!app.includes("sourceType:'conflict',sourceId:cf.id") || !app.includes("x.id===sid") || !app.includes('function migrateWorldMissionSource') || !app.includes("c.status==='active'&&(c.region===region||c.location===p.island)") || app.includes("sid.indexOf('|')>=0){var parts")) throw new Error('V2.5 conflict causal identity hardening missing');
if(!app.includes('function purgeSaveSlot') || !app.includes('function deleteSaveSlot') || !app.includes('save-delete')) throw new Error('V2.5 save deletion missing');
if(!app.includes('var ADAPTIVE_MISSION_TEMPLATES=') || !app.includes('function adaptiveMissionOpportunity') || !app.includes("m.adaptive?'adaptive:'")) throw new Error('V3.2 adaptive mission variety engine missing');
if(!app.includes("r.nemesisRecognized&&!r.challengeReady") || !app.includes("bonus['Poursuivre sa némésis']=2.0")) throw new Error('V2.9 nemesis pursuit pacing missing');
if(!app.includes('var MISSION_PROFILE_CONFIG=') || !app.includes('function missionResolution') || !app.includes('function missionChance')) throw new Error('V2.2 mission profile engine missing');
if(!app.includes('function styleMastery')) throw new Error('V2.2 style mastery missing');
if(!app.includes('debtInterestPaid') || !app.includes('function chargeMoney') || !app.includes('function serviceDebt')) throw new Error('V2.2 debt engine missing');
if(!app.includes("stats:{started:0,resolved:0,failed:0,abandoned:0,interrupted:0,choices:0}")) throw new Error('V2.2 narrative closure state missing');
if(!app.includes('factionRep') || !app.includes('Cipher Pol')) throw new Error('faction systems missing');
if(!app.includes('canonForecast') || !app.includes('contentStats')) throw new Error('V1 canon UI missing');
if(!app.includes('var ORG_CONFIG=') || !app.includes('var SHIP_TIERS=')) throw new Error('V1.6 organization configuration missing');
if(!app.includes('function organizationTick') || !app.includes('function organizationMissionDanger') || !app.includes('function recruitOrganizationMember')) throw new Error('V1.6 organization engine missing');
if(!app.includes('function upgradeOrganizationShip') || !app.includes('function syncOrganizationRole')) throw new Error('V1.6 command/ship engine missing');
if(!html.includes('id="organizationMembers"') || !html.includes('id="organizationResources"') || !html.includes('id="organizationActions"')) throw new Error('V1.6 organization UI missing');

if(!app.includes('function justiceTick') || !app.includes('function pursuitEncounter') || !app.includes('function arrestPlayer')) throw new Error('V1.6 pursuit/justice engine missing');
if(!app.includes('function prisonTick') || !app.includes('function attemptEscape') || !app.includes('function releaseFromPrison')) throw new Error('V1.6 prison engine missing');
if(!app.includes('function bountyTargets') || !app.includes('function huntBountyTarget')) throw new Error('V1.6 bounty hunting engine missing');
if(!app.includes('function registerCrime') || !app.includes('regionalHeat')) throw new Error('V1.6 crime/heat state missing');
if(!html.includes('id="wantedPoster"') || !html.includes('id="prisonSection"') || !html.includes('id="bountyTargets"')) throw new Error('V1.6 justice UI missing');
if(!app.includes('function influenceTick') || !app.includes('function influenceMetrics') || !app.includes('function evaluateTitles')) throw new Error('V1.6 influence engine missing');
if(!app.includes('function establishDomain') || !app.includes('function fortifyDomain') || !app.includes('function playerDomainDefense')) throw new Error('V1.6 domain engine missing');
if(!app.includes('function recruitAffiliate') || !app.includes('function affiliateCandidates')) throw new Error('V1.6 affiliate network missing');
if(!app.includes('function realignInfluenceAfterFactionChange')) throw new Error('V1.6 faction/domain realignment missing');
if(!html.includes('id="publicStanding"') || !html.includes('id="domainList"') || !html.includes('id="affiliateList"')) throw new Error('V1.6 influence UI missing');
const badDynamicLoops=[...app.matchAll(/(?<!\$)\$\([^;\n]*?\)\.forEach/g)];
if(badDynamicLoops.length) throw new Error('Single-element selector used as list: '+badDynamicLoops[0][0]);
if(!app.includes('function strategyTick') || !app.includes('function simulateWars') || !app.includes('function startStrategicWar')) throw new Error('V1.6 strategic war engine missing');
if(!app.includes('function createTreaty') || !app.includes('function simulateTreaties') || !app.includes('function coalitionFor')) throw new Error('V1.6 alliance engine missing');
if(!app.includes('function launchCampaign') || !app.includes('function supportStrategicWar') || !app.includes('function joinWarFront') || !app.includes('function proposeStrategicPeace')) throw new Error('V1.6 player strategy actions missing');
if(!html.includes('id="warList"') || !html.includes('id="treatyList"') || !html.includes('id="strategyActions"')) throw new Error('V1.6 strategic UI missing');
if(app.includes('$$$(')) throw new Error('Invalid $$$ selector helper found');
if(!app.includes('var TRADE_GOODS=') || !app.includes('function initWorldEconomy') || !app.includes('function simulateEconomy')) throw new Error('V1.6 world economy engine missing');
if(!app.includes('function buyCommodity') || !app.includes('function sellCommodity') || !app.includes('function cargoCapacity')) throw new Error('V1.6 cargo/trade engine missing');
if(!app.includes('function blackMarketAccess') || !app.includes('function inspectSmugglingAtArrival')) throw new Error('V1.6 black market/smuggling engine missing');
if(!app.includes('simulateEconomy();')) throw new Error('V1.6 economy is not connected to monthly world simulation');
if(!html.includes('id="marketGoods"') || !html.includes('id="cargoList"') || !html.includes('id="blackMarketSection"') || !html.includes('id="tradeRoutes"')) throw new Error('V1.6 trade UI missing');
if(!app.includes('if(!o)return 0;var ms=')) throw new Error('V1.6 organizationPower fix missing');
if(!app.includes("game={seed:seed,rng:{}};var origin=")) throw new Error('V1.6 Destiny seed bootstrap fix missing');
if(!app.includes('function commodityQuote') || !app.includes('function warBattleSidePower') || !app.includes('shockState')) throw new Error('V1.6 balance engine missing');
if(!app.includes('function combatRiskLabel')) throw new Error('V1.6 mission risk feedback missing');
if(!app.includes('function npcTick') || !app.includes('function bondCanonicalActor') || !app.includes('function relationPower')) throw new Error('V1.6 living NPC engine missing');
if(!app.includes('function trainWithMentor') || !app.includes('function challengeRival') || !app.includes('function recruitKnownRelation')) throw new Error('V1.6 mentor/rival/recruitment actions missing');
if(!app.includes('memories=Array.isArray') || !app.includes('npcPotential') || !app.includes('npcTrajectory')) throw new Error('V1.6 persistent NPC state missing');
if(!html.includes('id="bondDynamicsList"') || !html.includes('id="npcNetworkSummary"') || !html.includes('id="npcOpportunities"')) throw new Error('V1.6 living NPC UI missing');
if(!app.includes('function helpRelation') || !app.includes('function askRelationFavor') || !app.includes('favorBalance')) throw new Error('V1.6 social favors/debts missing');
if(!app.includes('function approachCanonicalActor')) throw new Error('V1.6 direct canonical interaction missing');
if(!app.includes('legacyRelations') || !app.includes("'legacy'")) throw new Error('V1.6 generational social memory missing');
if(!app.includes('linkedRelationId') || !app.includes('rr.npcPower')) throw new Error('V1.6 organization/relation synchronization missing');
if(!app.includes('function rivalStage') || !app.includes('function reconcileRival') || !app.includes('peerRecognized')) throw new Error('V1.6 relationship lifecycle arcs missing');
if(!app.includes('function realignRelationsAfterFactionChange') || !app.includes('political hostility') && !app.includes('tensions entre vos factions')) throw new Error('V1.6 faction/social integration missing');
if(!app.includes("r.npcAgeMonths<216") || !app.includes("r.npcAgeMonths<180")) throw new Error('V1.6 NPC age guards missing');
if(!app.includes('ageFactor=r.npcAgeMonths<144') || !app.includes('function npcCareerPromotionChance') || !app.includes('passiveCareerChance=')) throw new Error('V1.6 age-aware NPC lifecycle missing');
if(!app.includes('function migrateProgression') || !app.includes('function developmentFactor') || !app.includes('function attemptBreakthrough')) throw new Error('V1.7 progression engine missing');
if(!app.includes('naturalCaps') || !app.includes('absoluteCaps') || !app.includes('progressionSnapshot')) throw new Error('V1.7 layered progression state missing');
if(!app.includes('function progressionBar') || !app.includes('function renderProgressionOverview')) throw new Error('V1.7 progression UI missing');
if(!app.includes('function setupSectionNavigation') || !app.includes('function renderPanel') || !app.includes('renderPanel(activeTab)')) throw new Error('V1.7 lazy navigation engine missing');
if(!html.includes('id="characterSectionTabs"') || !html.includes('id="abilitiesSectionTabs"') || !html.includes('id="relationsSectionTabs"') || !html.includes('id="worldSectionTabs"')) throw new Error('V1.7 segmented navigation UI missing');
if(!html.includes('id="progressionSummary"') || !html.includes('id="progressionFocus"')) throw new Error('V1.7 progression dashboard missing');
if(app.includes('renderTimeline();renderChar();renderAb();renderRel();renderWorld()')) throw new Error('legacy full-screen render chain still active');
if(!app.includes('function defaultLifeLoop') || !app.includes('function advancePlan') || !app.includes('function chooseAdvanceDuration')) throw new Error('V1.8 adaptive time engine missing');
if(!app.includes('function eventChance') || !app.includes('function weightedEventPick') || !app.includes('function event(m,force)')) throw new Error('V1.8 event director missing');
if(!app.includes('function finalizeAdvanceReport') || !app.includes('function renderAdvanceLoop')) throw new Error('V1.8 advance feedback missing');
if(!html.includes('id="advanceRhythm"') || !html.includes('id="advanceReport"') || !html.includes('id="advanceReportStats"')) throw new Error('V1.8 life-loop UI missing');
if(!app.includes("loop.quietAdvances>=2")) throw new Error('V1.8 quiet-streak guard missing');
if(!app.includes('function defaultExploration') || !app.includes('function explorationSite') || !app.includes('function explorationTick')) throw new Error('V1.9 exploration engine missing');
if(!app.includes('function islandProfile') || !app.includes('function discoveryPool') || !app.includes('function registerDiscovery')) throw new Error('V1.9 island identity/discovery engine missing');
if(!app.includes('function routeEstimate') || !app.includes('function seaJourneyTick') || !app.includes('function renderJourney')) throw new Error('V1.9 sea journey engine missing');
if(!app.includes('function currentRumor') || !app.includes('function learnLocalRumor')) throw new Error('V1.9 rumor engine missing');
if(!app.includes('function renderCodexExploration')) throw new Error('V1.9 Codex exploration integration missing');
if(!html.includes('id="explorationSummary"') || !html.includes('id="localDiscoveries"') || !html.includes('id="seaJourneyCard"') || !html.includes('id="codexSummary"')) throw new Error('V1.9 exploration UI missing');
if(!app.includes("id:'explorer'") || !app.includes("id:'discoverer'") || !app.includes("id:'cartographer'")) throw new Error('V1.9 exploration achievements missing');
if(!app.includes('function defaultStoryEngine') || !app.includes('function migrateStoryEngine') || !app.includes('function storyTick')) throw new Error('V2.0 story engine missing');
if(!app.includes('function startStory') || !app.includes('function storyChoice') || !app.includes('function storyResolve')) throw new Error('V2.0 story lifecycle missing');
if(!app.includes('function showStoryDecision') || !app.includes('function renderStories') || !app.includes('function awaitingStory')) throw new Error('V2.0 story decision/UI integration missing');
if(!html.includes('id="storyEngineBadge"') || !html.includes('id="storySummary"') || !html.includes('id="activeStories"') || !html.includes('id="storyHistory"')) throw new Error('V2.0 story UI missing');
if(!app.includes("id:'story-first'") || !app.includes("id:'story-weaver'") || !app.includes("id:'story-decisions'")) throw new Error('V2.0 story achievements missing');
if(!app.includes("if(awaitingStory())return showStoryDecision()")) throw new Error('V2.0 AVANCER story gate missing');
console.log('ONE PIECE LIFE V5.0 validation OK');

if(!app.includes('function missionOutcomeFlavor') || !app.includes('function endgameMilestones') || !app.includes('function migrateWorldFoundations') || !app.includes('function worldStateSummary') || !app.includes("id==='navigation'") || !app.includes("id==='trade'")) throw new Error('V3.2 career-specific mission outcomes missing');

if(!app.includes('function simulateWorldSagas') || !app.includes('function playerWorldRecognition') || !app.includes('function updateFactionWorldGoals') || !app.includes('function playerSagaPresence')) throw new Error('V4.0 Living World systems missing');
if(!app.includes("ws.canonBranches.filter(function(x){return x&&x.status==='active'}") || !app.includes("ws.worldSagas.filter(function(x){return x&&x.status==='active'}") || !app.includes("ws.worldSagas=ws.worldSagas.filter(function(x){return x.status==='active'}") || !app.includes("ws.canonBranches=ws.canonBranches.filter(function(b){return b.status==='active'}")) throw new Error('V5.0 resolved world-state pruning missing');
if(!app.includes("ws.actorHistory.slice(0,90)") || !app.includes("ws.territoryHistory.slice(0,80)") || !app.includes("ws.sagaHistory.slice(0,60)") || !app.includes("ws.crewHistory.slice(0,70)")) throw new Error('V5.0 recent-first world history migration missing');
if(!app.includes('function defaultLifeDirector') || !app.includes('function directorTravelContext') || !app.includes('function directorTravelCandidate') || !app.includes('function directorRomanceCandidate') || !app.includes('function directorFamilyOpportunity') || !app.includes('function beginJourney')) throw new Error('V5.0 Grand Journey Life Director missing');
if(!app.includes("p.ambition==='Explorer le monde'&&fresh") || !app.includes('backtrackPenalty') || !app.includes("h.kind==='mobility'")) throw new Error('V5.0 personalized journey routing missing');
if(!app.includes('function careerMomentumFactor') || !app.includes('function updateCareerMomentum') || !app.includes('function recordCareerMissionEvidence') || !app.includes('recentResults') || !app.includes('distinctions') || !app.includes('rec.momentum*=Math.pow(.985,m)')) throw new Error('V5.0 career trajectory engine missing');
if(!app.includes('function careerSpecializationFit') || !app.includes('function careerTurnCandidate') || !app.includes('function applyCareerSpecialization') || !app.includes("story.type==='career-turn'") || !app.includes('lastCareerTurnAge')) throw new Error('V5.0 organic career turning points missing');
if(!app.includes('function careerPerformanceReview') || !app.includes("Dossier global '+Math.round(review.successRate*100)") || !app.includes("Distinctions '+review.distinctions+' / '+review.neededDistinctions") || !app.includes("neededDistinctions=index>=3?Math.max(2,(index-2)*2):0") || !app.includes("familyFuture==='child'?1.55:1.28")) throw new Error('V5.0 promotion review or family pacing missing');
if(!app.includes('function signalPersonalChapter') || !app.includes('function closePersonalChapter') || !app.includes('function personalChapterTick') || !app.includes('function visiblePersonalChapter') || !app.includes('chapterHistory')) throw new Error('V5.0 personal chapter engine missing');
if(!app.includes('function generationLegacySnapshot') || !app.includes('g.dynasty.ancestors.slice(-20)') || !app.includes('legacy:legacy')) throw new Error('V5.0 bounded generational legacy missing');
if(!app.includes('function latestDynastyLegacy') || !app.includes("Héritage de '+e(ancestor.name)")) throw new Error('V5.0 visible generational legacy missing');
if(!app.includes("Chapitre actuel : ")) throw new Error('V5.0 active chapter is not surfaced in AVANCER');
if(!app.includes('partnerFollows') || !app.includes('longDistance') || !app.includes("Vous vous installez ensemble à")) throw new Error('V5.0 household relocation continuity missing');
if(!app.includes('function settleCareerNetwork') || !app.includes("if(r.id===p.life.partnerId&&!r.longDistance)")) throw new Error('V5.0 relocation social continuity missing');
if(!app.includes('function directorMobilityWording') || !app.includes("f==='Pirates')return{noun:'nouveau cap'")) throw new Error('V5.0 faction-aware journey wording missing');
if(!app.includes("overdueTransfer=!!(transfer&&p.ageMonths-(director.lastMobilityAge||-999)>=54)") || !app.includes("overdueTransfer&&R('story')<.78?'career-transfer'")) throw new Error('V5.0 overdue journey priority missing');
if(!app.includes('repeatPenalty=(m.novelty||1)<.10?.48') || !app.includes("safePool=safeOptions.filter(function(x){return x.chance>=topSafe-.08&&(x.novelty||1)>.10})")) throw new Error('V5.0 mission variety protection missing');
