import fs from 'node:fs';

const app=fs.readFileSync('app.js','utf8');
const html=fs.readFileSync('index.html','utf8');
const manifest=fs.readFileSync('manifest.webmanifest','utf8');
const pack=fs.readFileSync('content-v1.js','utf8');
const sw=fs.readFileSync('sw.js','utf8');

new Function(app);
new Function(pack);
JSON.parse(manifest);

if(!html.includes('V2.4')) throw new Error('index.html does not expose V2.4');
if(!app.includes('version:24') || !app.includes('g.version=24')) throw new Error('game state is not V2.4 migration version 24');
if(!html.includes('<script src="content-v1.js"></script>')) throw new Error('content pack is not loaded');
if(html.indexOf('content-v1.js')>html.indexOf('app.js')) throw new Error('content pack must load before app.js');
if(!sw.includes('content-v1.js')) throw new Error('PWA cache does not include content-v1.js');

const dynamicIds=new Set(['eatHeldFruit','challengeBtn','martialTrainBtn','changeCareerBtn','careerRecordBtn','upgradeHousingBtn','investBusinessBtn','partnerTimeBtn','marryBtn','breakupBtn','welcomeChildBtn','orgBondBtn','orgRecruitBtn','orgTrainBtn','orgFundBtn','orgSupplyBtn','orgRepairBtn','orgUpgradeBtn','layLowBtn','surrenderBtn','escapeBtn','claimDomainBtn','fortifyDomainBtn','affiliateCrewBtn','launchCampaignBtn','seekMentorBtn','exploreIslandBtn','seekRumorBtn','specializationChoiceBtn','ambitionChoiceBtn','timelineMoreBtn','expandRelationsBtn']);
const ids=[...app.matchAll(/\$\('#([^']+)'\)/g)].map(m=>m[1]);
const missing=[...new Set(ids)].filter(id=>!dynamicIds.has(id)&&!html.includes('id="'+id+'"'));
if(missing.length) throw new Error('Missing HTML ids: '+missing.join(', '));

if(!app.includes('function careerTick') || !app.includes('var CAREERS=')) throw new Error('career engine missing');
if(!app.includes('function worldMonthStep') || !app.includes('function simulateCrews') || !app.includes('function simulateActors') || !app.includes('function simulateConflicts')) throw new Error('living world engine missing');
if(!app.includes('function lifeTick') || !app.includes('function continueWithHeir') || !app.includes('function checkAchievements')) throw new Error('life simulator engine missing');
if(!app.includes('function processCanonEvents') || !app.includes('function resolveCanonEvent')) throw new Error('V1 causal canon engine missing');
if(!app.includes('CANON_EVENTS') || !app.includes('SPECIAL_TECHNIQUES') || !app.includes('pickFruit')) throw new Error('V1 content integration missing');
if(!app.includes('relationshipStatus') || !app.includes('children') || !app.includes('netWorthPeak')) throw new Error('family/economy state missing');
if(!app.includes("Mobilité:{keys:['Vitesse','Agilité']") || !app.includes("Mental:{keys:['Volonté','Discipline']")) throw new Error('V2.1 focused progression profiles missing');
if(!app.includes('var SPEC_PROFILES=') || !app.includes('function careerQualification') || !app.includes('function careerActivityFit')) throw new Error('V2.2 meaningful career engine missing');
if(!app.includes('var SIMPLE_FOCUS=') || !app.includes('function recommendedFocus') || !app.includes('function normalizeActivityFocus')) throw new Error('V2.3 adaptive focus engine missing');
if(!app.includes("label:'Progresser'") || !app.includes("label:'Situation'") || !app.includes("label:'Monde'")) throw new Error('V2.3 simplified navigation missing');
if(!app.includes('function specializationDecision') || !app.includes('function ambitionDecision')) throw new Error('V2.3 simplified choice flows missing');
if(!app.includes("'Auto':{label:'Auto'") || !app.includes("if(p.focus==='Auto')return recommendedFocus()")) throw new Error('V2.4 Auto focus missing');
if(!app.includes("min:3,max:5") || !app.includes("min:2,max:4")) throw new Error('V2.4 flow pacing missing');
if(!app.includes('function renderWorldExplore') || !app.includes('function renderWorldState') || !app.includes('function renderWorldHistory')) throw new Error('V2.4 lazy world rendering missing');
if(!app.includes('function renderRelClose') || !app.includes('function renderRelNetwork') || !app.includes('function relationActionDecision')) throw new Error('V2.4 contextual relation UI missing');
if(!app.includes('function renderAbProgress') || !app.includes('function renderAbPowers') || !app.includes('function renderAbDetails')) throw new Error('V2.4 lazy progression rendering missing');
if(!app.includes("activityGrowthKeys(currentFocus())")) throw new Error('V2.4 focus-aware event engine missing');
if(!app.includes('var MISSION_PROFILE_CONFIG=') || !app.includes('function missionResolution') || !app.includes('function missionChance')) throw new Error('V2.2 mission profile engine missing');
if(!app.includes('function styleMastery')) throw new Error('V2.2 style mastery missing');
if(!app.includes('debtInterestPaid') || !app.includes('function chargeMoney') || !app.includes('function serviceDebt')) throw new Error('V2.2 debt engine missing');
if(!app.includes("stats:{started:0,resolved:0,failed:0,abandoned:0,interrupted:0,choices:0}")) throw new Error('V2.2 narrative closure state missing');
if(!app.includes('factionRep') || !app.includes('Cipher Pol')) throw new Error('faction systems missing');
if(!app.includes('canonForecast') || !app.includes('contentStats')) throw new Error('V1 canon UI missing');
if(!app.includes('var ORG_CONFIG=') || !app.includes('var SHIP_TIERS=')) throw new Error('V1.6 organization configuration missing');
if(!app.includes('function organizationTick') || !app.includes('function organizationMissionDanger') || !app.includes('function recruitOrganizationMember')) throw new Error('V1.6 organization engine missing');
if(!app.includes('function upgradeOrganizationShip') || !app.includes('function syncOrganizationRole')) throw new Error('V1.6 command/ship engine missing');
if(!html.includes('id="organizationMembers"') || !html.includes('id="organizationResources"') || !html.includes('id="organizationActions"')) throw new Error('V1.6 organization UI missing');

if(!app.includes('function justiceTick') || !app.includes('function pursuitEncounter') || !app.includes('function arrestPlayer')) throw new Error('V1.6 pursuit/justice engine missing');
if(!app.includes('function prisonTick') || !app.includes('function attemptEscape') || !app.includes('function releaseFromPrison')) throw new Error('V1.6 prison engine missing');
if(!app.includes('function bountyTargets') || !app.includes('function huntBountyTarget')) throw new Error('V1.6 bounty hunting engine missing');
if(!app.includes('function registerCrime') || !app.includes('regionalHeat')) throw new Error('V1.6 crime/heat state missing');
if(!html.includes('id="wantedPoster"') || !html.includes('id="prisonSection"') || !html.includes('id="bountyTargets"')) throw new Error('V1.6 justice UI missing');
if(!app.includes('function influenceTick') || !app.includes('function influenceMetrics') || !app.includes('function evaluateTitles')) throw new Error('V1.6 influence engine missing');
if(!app.includes('function establishDomain') || !app.includes('function fortifyDomain') || !app.includes('function playerDomainDefense')) throw new Error('V1.6 domain engine missing');
if(!app.includes('function recruitAffiliate') || !app.includes('function affiliateCandidates')) throw new Error('V1.6 affiliate network missing');
if(!app.includes('function realignInfluenceAfterFactionChange')) throw new Error('V1.6 faction/domain realignment missing');
if(!html.includes('id="publicStanding"') || !html.includes('id="domainList"') || !html.includes('id="affiliateList"')) throw new Error('V1.6 influence UI missing');
const badDynamicLoops=[...app.matchAll(/(?<!\$)\$\([^;\n]*?\)\.forEach/g)];
if(badDynamicLoops.length) throw new Error('Single-element selector used as list: '+badDynamicLoops[0][0]);
if(!app.includes('function strategyTick') || !app.includes('function simulateWars') || !app.includes('function startStrategicWar')) throw new Error('V1.6 strategic war engine missing');
if(!app.includes('function createTreaty') || !app.includes('function simulateTreaties') || !app.includes('function coalitionFor')) throw new Error('V1.6 alliance engine missing');
if(!app.includes('function launchCampaign') || !app.includes('function supportStrategicWar') || !app.includes('function joinWarFront') || !app.includes('function proposeStrategicPeace')) throw new Error('V1.6 player strategy actions missing');
if(!html.includes('id="warList"') || !html.includes('id="treatyList"') || !html.includes('id="strategyActions"')) throw new Error('V1.6 strategic UI missing');
if(app.includes('$$$(')) throw new Error('Invalid $$$ selector helper found');
if(!app.includes('var TRADE_GOODS=') || !app.includes('function initWorldEconomy') || !app.includes('function simulateEconomy')) throw new Error('V1.6 world economy engine missing');
if(!app.includes('function buyCommodity') || !app.includes('function sellCommodity') || !app.includes('function cargoCapacity')) throw new Error('V1.6 cargo/trade engine missing');
if(!app.includes('function blackMarketAccess') || !app.includes('function inspectSmugglingAtArrival')) throw new Error('V1.6 black market/smuggling engine missing');
if(!app.includes('simulateEconomy();')) throw new Error('V1.6 economy is not connected to monthly world simulation');
if(!html.includes('id="marketGoods"') || !html.includes('id="cargoList"') || !html.includes('id="blackMarketSection"') || !html.includes('id="tradeRoutes"')) throw new Error('V1.6 trade UI missing');
if(!app.includes('if(!o)return 0;var ms=')) throw new Error('V1.6 organizationPower fix missing');
if(!app.includes("game={seed:seed,rng:{}};var origin=")) throw new Error('V1.6 Destiny seed bootstrap fix missing');
if(!app.includes('function commodityQuote') || !app.includes('function warBattleSidePower') || !app.includes('shockState')) throw new Error('V1.6 balance engine missing');
if(!app.includes('function combatRiskLabel')) throw new Error('V1.6 mission risk feedback missing');
if(!app.includes('function npcTick') || !app.includes('function bondCanonicalActor') || !app.includes('function relationPower')) throw new Error('V1.6 living NPC engine missing');
if(!app.includes('function trainWithMentor') || !app.includes('function challengeRival') || !app.includes('function recruitKnownRelation')) throw new Error('V1.6 mentor/rival/recruitment actions missing');
if(!app.includes('memories=Array.isArray') || !app.includes('npcPotential') || !app.includes('npcTrajectory')) throw new Error('V1.6 persistent NPC state missing');
if(!html.includes('id="bondDynamicsList"') || !html.includes('id="npcNetworkSummary"') || !html.includes('id="npcOpportunities"')) throw new Error('V1.6 living NPC UI missing');
if(!app.includes('function helpRelation') || !app.includes('function askRelationFavor') || !app.includes('favorBalance')) throw new Error('V1.6 social favors/debts missing');
if(!app.includes('function approachCanonicalActor')) throw new Error('V1.6 direct canonical interaction missing');
if(!app.includes('legacyRelations') || !app.includes("'legacy'")) throw new Error('V1.6 generational social memory missing');
if(!app.includes('linkedRelationId') || !app.includes('rr.npcPower')) throw new Error('V1.6 organization/relation synchronization missing');
if(!app.includes('function rivalStage') || !app.includes('function reconcileRival') || !app.includes('peerRecognized')) throw new Error('V1.6 relationship lifecycle arcs missing');
if(!app.includes('function realignRelationsAfterFactionChange') || !app.includes('political hostility') && !app.includes('tensions entre vos factions')) throw new Error('V1.6 faction/social integration missing');
if(!app.includes("r.npcAgeMonths<216") || !app.includes("r.npcAgeMonths<180")) throw new Error('V1.6 NPC age guards missing');
if(!app.includes('ageFactor=r.npcAgeMonths<144') || !app.includes('r.npcAgeMonths>=180&&R')) throw new Error('V1.6 age-aware NPC lifecycle missing');
if(!app.includes('function migrateProgression') || !app.includes('function developmentFactor') || !app.includes('function attemptBreakthrough')) throw new Error('V1.7 progression engine missing');
if(!app.includes('naturalCaps') || !app.includes('absoluteCaps') || !app.includes('progressionSnapshot')) throw new Error('V1.7 layered progression state missing');
if(!app.includes('function progressionBar') || !app.includes('function renderProgressionOverview')) throw new Error('V1.7 progression UI missing');
if(!app.includes('function setupSectionNavigation') || !app.includes('function renderPanel') || !app.includes('renderPanel(activeTab)')) throw new Error('V1.7 lazy navigation engine missing');
if(!html.includes('id="characterSectionTabs"') || !html.includes('id="abilitiesSectionTabs"') || !html.includes('id="relationsSectionTabs"') || !html.includes('id="worldSectionTabs"')) throw new Error('V1.7 segmented navigation UI missing');
if(!html.includes('id="progressionSummary"') || !html.includes('id="progressionFocus"')) throw new Error('V1.7 progression dashboard missing');
if(app.includes('renderTimeline();renderChar();renderAb();renderRel();renderWorld()')) throw new Error('legacy full-screen render chain still active');
if(!app.includes('function defaultLifeLoop') || !app.includes('function advancePlan') || !app.includes('function chooseAdvanceDuration')) throw new Error('V1.8 adaptive time engine missing');
if(!app.includes('function eventChance') || !app.includes('function weightedEventPick') || !app.includes('function event(m,force)')) throw new Error('V1.8 event director missing');
if(!app.includes('function finalizeAdvanceReport') || !app.includes('function renderAdvanceLoop')) throw new Error('V1.8 advance feedback missing');
if(!html.includes('id="advanceRhythm"') || !html.includes('id="advanceReport"') || !html.includes('id="advanceReportStats"')) throw new Error('V1.8 life-loop UI missing');
if(!app.includes("loop.quietAdvances>=2")) throw new Error('V1.8 quiet-streak guard missing');
if(!app.includes('function defaultExploration') || !app.includes('function explorationSite') || !app.includes('function explorationTick')) throw new Error('V1.9 exploration engine missing');
if(!app.includes('function islandProfile') || !app.includes('function discoveryPool') || !app.includes('function registerDiscovery')) throw new Error('V1.9 island identity/discovery engine missing');
if(!app.includes('function routeEstimate') || !app.includes('function seaJourneyTick') || !app.includes('function renderJourney')) throw new Error('V1.9 sea journey engine missing');
if(!app.includes('function currentRumor') || !app.includes('function learnLocalRumor')) throw new Error('V1.9 rumor engine missing');
if(!app.includes('function renderCodexExploration')) throw new Error('V1.9 Codex exploration integration missing');
if(!html.includes('id="explorationSummary"') || !html.includes('id="localDiscoveries"') || !html.includes('id="seaJourneyCard"') || !html.includes('id="codexSummary"')) throw new Error('V1.9 exploration UI missing');
if(!app.includes("id:'explorer'") || !app.includes("id:'discoverer'") || !app.includes("id:'cartographer'")) throw new Error('V1.9 exploration achievements missing');
if(!app.includes('function defaultStoryEngine') || !app.includes('function migrateStoryEngine') || !app.includes('function storyTick')) throw new Error('V2.0 story engine missing');
if(!app.includes('function startStory') || !app.includes('function storyChoice') || !app.includes('function storyResolve')) throw new Error('V2.0 story lifecycle missing');
if(!app.includes('function showStoryDecision') || !app.includes('function renderStories') || !app.includes('function awaitingStory')) throw new Error('V2.0 story decision/UI integration missing');
if(!html.includes('id="storyEngineBadge"') || !html.includes('id="storySummary"') || !html.includes('id="activeStories"') || !html.includes('id="storyHistory"')) throw new Error('V2.0 story UI missing');
if(!app.includes("id:'story-first'") || !app.includes("id:'story-weaver'") || !app.includes("id:'story-decisions'")) throw new Error('V2.0 story achievements missing');
if(!app.includes("if(awaitingStory())return showStoryDecision()")) throw new Error('V2.0 AVANCER story gate missing');
console.log('ONE PIECE LIFE V2.4 validation OK');
